### ISSUE TITLE
Crashes if a profiled function defines a non-class using the name `cls`

### ISSUE THREAD

**Issue by SnoopJeDi** [plasma-umass/scalene#193]
**Describe the bug**
Scalene tries to retrieve `__name__` from any value named `cls`, even if this attribute is not present, causing an unhandled `AttributeError`

**To Reproduce**

Running Scalene on the following program:

```python
# repro.py
import time

def f():
    cls = "This value isn't a class"
    time.sleep(0.5)  # to be sure this frame gets sampled

f()
```

yields the output:

```
$ python3 -m scalene repro.py 
Error in program being profiled:
 'str' object has no attribute '__name__'
Traceback (most recent call last):
  File "/home/snoopjedi/repos/scalene/scalene/scalene_profiler.py", line 1241, in profile_code
    exec(code, the_globals, the_locals)
  File "repro.py", line 8, in <module>
    f()
  File "repro.py", line 5, in f
    time.sleep(0.5)  # to be sure this frame gets sampled
  File "/home/snoopjedi/repos/scalene/scalene/scalene_profiler.py", line 488, in cpu_signal_handler
    Scalene.cpu_signal_handler_helper(signum, this_frame)
  File "/home/snoopjedi/repos/scalene/scalene/scalene_profiler.py", line 604, in cpu_signal_handler_helper
    Scalene.enter_function_meta(frame, Scalene.__stats)
  File "/home/snoopjedi/repos/scalene/scalene/scalene_profiler.py", line 775, in enter_function_meta
    prepend_name = f.f_locals["cls"].__name__
AttributeError: 'str' object has no attribute '__name__'
Scalene: Program did not run for long enough to profile.
```

**Expected behavior**
Scalene proceeds as if the name was not defined, i.e. without prepending anything to `f_name`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version `scalene 1.3.4.7`
 - I have observed the fault on a non-editable install of the library as well as the editable install shown above.

**Additional context**
Failure was first observed when profiling a program that indirectly invoked [`matplotlib.font_manager._json_decode()`](https://github.com/matplotlib/matplotlib/blob/69b51f1f4e7f8bab684fdf925ef8e2f94bbf2031/lib/matplotlib/font_manager.py#L932-L947)

It looks like cd5b7e7 may have been intended to address this problem. I can't find an associated issue.

**Comment by SnoopJeDi** [comment]
PR is open as #194 

Note: this PR preserves Scalene's behavior of assuming that anything named `cls` in the target frame's locals may be a class, but this is still susceptible to false positives, as in this admittedly pathological example:

```python
import time

def f():
    def cls():
        """This function isn't a class, but it does have a __name__"""
        return 42
    time.sleep(0.5)

f()
```

Which produces output that erroneously refers to `f()` as `cls.f`. This seems like it's probably not enough of an edge case to worry about, but if a slightly higher-fidelity detection of `@classmethod` is desirable, Scalene might use `inspect.isclass()` to limit the prepend behavior to true classes (easy) and/or inspect the signature of the relevant callable (hard).
