### ISSUE TITLE
Using --cpu-only flag fails with AttributeError

### ISSUE THREAD

**Issue by tbabej** [plasma-umass/scalene#230]
Running scalene on any source code with `--cpu-only` flag enabled fails on the newest `1.3.7` release:

```
$ python3 -m scalene --version
Scalene version 1.3.7

$ python3 -m scalene --cpu-only bug.py
Scalene: An exception of type AttributeError occurred. Arguments:
("type object 'Scalene' has no attribute '_Scalene__malloc_lock_mmap'",)
Traceback (most recent call last):
  File "/lib64/python3.9/site-packages/scalene/scalene_profiler.py", line 1313, in run_profiler
    exit_status = profiler.profile_code(
  File "/lib64/python3.9/site-packages/scalene/scalene_profiler.py", line 1190, in profile_code
    self.start()
  File "/lib64/python3.9/site-packages/scalene/scalene_profiler.py", line 1115, in start
    Scalene.clear_mmap_data()
  File "/lib64/python3.9/site-packages/scalene/scalene_profiler.py", line 1108, in clear_mmap_data
    while Scalene.read_malloc_mmap(): pass
  File "/lib64/python3.9/site-packages/scalene/scalene_profiler.py", line 809, in read_malloc_mmap
    Scalene.__malloc_lock_mmap,
AttributeError: type object 'Scalene' has no attribute '_Scalene__malloc_lock_mmap'
```

where bug.py contains the following (single line of) code:
```python
print(42)
```

**Comment by jaltmayerpizzorno** [comment]
Hi, this should be fixed now (in 1.3.8).  Please re-open if you see it again.

**Comment by jaltmayerpizzorno** [comment]
Thank you for reporting it!

**Comment by tbabej** [comment]
I can confirm this fixes the issue. Thanks for the fast fix!
