### ISSUE TITLE
pynvml.NVMLError_NotSupported prevents execution

### ISSUE THREAD

**Issue by sgdecker** [plasma-umass/scalene#262]
I am trying to profile a Python code that doesn't use the GPU on a CentOS 7 machine inside a conda environment into which I pip installed scalene.

Here's what I get:
```
> scalene --reduced-profile --cpu-only --html --outfile upa.html upa_bug.py
Error in program being profiled:
 Not Supported
Traceback (most recent call last):
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "upa_bug.py", line 1, in <module>
    import metpy
  File "/home/decker/src/git_repos/metpy/src/metpy/__init__.py", line 35, in <module>
    from .xarray import *  # noqa: F401, F403, E402
  File "/home/decker/src/git_repos/metpy/src/metpy/xarray.py", line 26, in <module>
    import numpy as np
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/numpy/core/multiarray.py", line 614, in <module>
    def min_scalar_type(a):
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/numpy/core/overrides.py", line 224, in decorator
    return array_function_dispatch(
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/numpy/core/overrides.py", line 197, in decorator
    source_object = compile(
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/scalene/scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "/home/decker/local/miniconda3/envs/devel21/lib/python3.9/site-packages/pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_NotSupported: Not Supported
Scalene: Program did not run for long enough to profile.

```

Is there a workaround for this, particularly as the GPU profiling is not relevant in my case?

**Comment by lfaucheux** [comment]
Waiting for a stable fix, I added `raise RuntimeError("Let's do without it for now !")` at line 12 of `%PYTHON_ROOT%\lib\site-packages\scalene\scalene_gpu.py`.

**Comment by leshchenko1979** [comment]
It seems like I have a similar issue.

I'm trying to profile a code on a laptop with built-in graphics and I get the following error:
```
Error in program being profiled:
 Unknown Error
Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "anal_b.py", line 80, in <module>
    print(check_all_variants(temp, subs))
Scalene: An exception of type NVMLError_Unknown occurred. Arguments:
(999,)
Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "anal_b.py", line 80, in <module>
    print(check_all_variants(temp, subs))
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  [Previous line repeated 5 more times]
  File "anal_b.py", line 33, in check_all_variants
    elif idx % 2:  # если четный, то должен быть выше
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1320, in run_profiler
    exit_status = profiler.profile_code(
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1207, in profile_code
    traceback.print_exc()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 163, in print_exc 
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error
Scalene failed to initialize.
Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "anal_b.py", line 80, in <module>
    print(check_all_variants(temp, subs))
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  [Previous line repeated 5 more times]
  File "anal_b.py", line 33, in check_all_variants
    elif idx % 2:  # если четный, то должен быть выше
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1320, in run_profiler
    exit_status = profiler.profile_code(
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1207, in profile_code
    traceback.print_exc()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 163, in print_exc 
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1334, in run_profiler
    print(traceback.format_exc())
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error
ERROR: Calling scalene main function failed: Unknown Error
Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "anal_b.py", line 80, in <module>
    print(check_all_variants(temp, subs))
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  [Previous line repeated 5 more times]
  File "anal_b.py", line 33, in check_all_variants
    elif idx % 2:  # если четный, то должен быть выше
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1320, in run_profiler
    exit_status = profiler.profile_code(
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1207, in profile_code
    traceback.print_exc()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 163, in print_exc 
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\inspect.py", line 1503, in getframeinfo
    lines, lnum = findsource(frame)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\inspect.py", line 829, in findsource  
    module = getmodule(object, file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\inspect.py", line 755, in getmodule   
    os.path.realpath(f)] = module.__name__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 647, in realpath     
    path = _getfinalpathname(path)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

Original exception was:
Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "anal_b.py", line 80, in <module>
    print(check_all_variants(temp, subs))
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  File "anal_b.py", line 41, in check_all_variants
    res = check_all_variants(temp[:idx] + [el] + temp[idx + 1 :], subs[:i] + subs[i + 1: ])
  [Previous line repeated 5 more times]
  File "anal_b.py", line 33, in check_all_variants
    elif idx % 2:  # если четный, то должен быть выше
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1320, in run_profiler
    exit_status = profiler.profile_code(
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1207, in profile_code
    traceback.print_exc()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 163, in print_exc 
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1334, in run_profiler
    print(traceback.format_exc())
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\__main__.py", line 7, in main
    scalene_profiler.Scalene.main()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1241, in main
    Scalene.run_profiler(args, left)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1343, in run_profiler
    print("Scalene failed to initialize.\n" + traceback.format_exc())
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_gpu.py", line 37, in load
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code      
    exec(code, run_globals)
  File "C:\Users\leshc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\scalene.exe\__main__.py", line 7, in <module>
```

**Comment by emeryberger** [comment]
Please try installing from the repo version - in theory, it should fix this issue. 

`python3 -m pip install git+https://github.com/plasma-umass/scalene`

Thanks!

**Comment by emeryberger** [comment]
Closing, fixed in latest release.
