### ISSUE TITLE
Scalene: internal error: unable to find Python allocator functions

### ISSUE THREAD

**Issue by didimelli** [plasma-umass/scalene#278]
**Describe the bug**
When starting `scalene` (with `poetry run python -m scalene my_script.py`), I get the error `Scalene: internal error: unable to find Python allocator functions`. This happens both with `poetry run python -m scalene my_script.py` or if started within the venv (`python -m scalene my_script.py` or just `scalene my_script.py`).

Some seconds after this output, i get a long traceback (reported afterwards).

I don't really think this is something about my program, since it always worked without `scalene`, but I think it is something related to Trio.

**To Reproduce**

Snippet that cause the error:
```python
#asd.py

import time
import trio
time.sleep(3)
```

and then `poetry run python -m scalene asd.py`. This gives this traceback:
```
Error in program being profiled:
 string index out of range
Traceback (most recent call last):
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 1326, in profile_code
    exec(code, the_globals, the_locals)
  File "asd.py", line 2, in <module>
    import trio
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/trio/__init__.py", line 48, in <module>
    from ._sync import (
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/trio/_sync.py", line 475, in <module>
    @attr.s(eq=False, hash=False, repr=False)
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/attr/_make.py", line 1312, in wrap
    field_transformer,
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/attr/_make.py", line 610, in __init__
    field_transformer,
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/attr/_make.py", line 503, in _transform_attrs
    AttrsClass = _make_attr_tuple_class(cls.__name__, attr_names)
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/attr/_make.py", line 299, in _make_attr_tuple_class
    eval(compile("\n".join(attr_class_template), "", "exec"), globs)
  File "", line 1, in <module>
  File "/home/didi/leaf/leaf-radio/.venv/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 231, in invalidate_lines
    if f.f_code.co_filename[0] == "<" or "scalene" in f.f_code.co_filename:
IndexError: string index out of range
```

Commenting out the line `import trio`, makes everything works.

However, the line `Scalene: internal error: unable to find Python allocator functions` is always present.

**Desktop (please complete the following information):**
 - OS: WSL2
 - Python version: 3.7.10, installed with pyenv
 - Scalene version: 1.3.15

**Comment by didimelli** [comment]
Awesome! Let me know if you need any info about my environment for the allocator function issue!

**Comment by didimelli** [comment]
Hi! Done what you proposed about the local dependency, and i still get the allocator function issue. The trio one is gone though!
![image](https://user-images.githubusercontent.com/53627721/136654662-e9431528-9cfe-408d-b094-6bb20ef4b5d9.png)

Let me know if I can do (and how) some debugging on my side (logging, ...)

**Comment by sternj** [comment]
Replicated on python 3.7.10, does not arise on 3.8.10. Attempting on 3.7.12

**Comment by sternj** [comment]
This seems to be a python3.7 issue instead of a Poetry issue

**Comment by didimelli** [comment]
I made a 3.8 environment using the same tools (pyenv, poetry, scalene as a local dep, ...) and the allocator function issue does not appear. So no pyenv nor poetry seem to be related to the issue.

**Comment by sternj** [comment]
I need to verify this by doing a binary install of Python 3.7, but it appears to be either a python 3.7 issue or an issue with the interaction between Pyenv and Python 3.7. Pyenv starts up a bunch of child processes and for some reason one of the children doesn't load `libpython`

**Comment by tungdam** [comment]
I have the same issue with python 3.7.3 
```
[root@tungdam10-virt.dev:/tmp]# cat test.py
import time
print("hello")
time.sleep(3)

[root@tungdam10-virt.dev:/tmp]# scalene test.py
Scalene: internal error: unable to find Python allocator functions
hello
....
```

First time i try scalene so not sure if i did anything wrong. Advice please

**Comment by ijpulidos** [comment]
I can confirm the issue appearing with python 3.9.7 in a conda environment.

**Comment by michellehoog** [comment]
Getting the same error on WSL2, running a conda environment with python 3.7.11. I still get profiling information from scalene, but the message is always present.
