### ISSUE TITLE
pip install fails in conda environment windows 10 and python 3.9

### ISSUE THREAD

**Issue by ywilke** [plasma-umass/scalene#305]
**Describe the bug**
Scalene 1.3.16 and 1.3.15 fail to install with pip on windows 10.

**To Reproduce**
1. Setup fresh conda environment with python 3.9 on windows 10
2. pip install scalene
3. See error

**Expected behavior**
Pip installs latest version of scalene.

**Desktop (please complete the following information):**
 - OS: Windows 10
- Python 3.9
- Conda 4.11

**Additional context**
It ends up installing scalene 1.3.12. This version does not seem to work. It crashes when trying to profile a really simple script. Not sure if I should also make a issue for that problem.

This is the error when installing scalene with pip:
`````
(scalene) C:\Users\Yano>pip install scalene
Collecting scalene
  Using cached scalene-1.3.16.tar.gz (2.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Yano\miniconda3\envs\scalene\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yano\\AppData\\Local\\Temp\\pip-install-6hj9rjyr\\scalene_09d2c173db09414b8ea4502001e4918f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yano\\AppData\\Local\\Temp\\pip-install-6hj9rjyr\\scalene_09d2c173db09414b8ea4502001e4918f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Yano\AppData\Local\Temp\pip-pip-egg-info-4jmg1t0w'
         cwd: C:\Users\Yano\AppData\Local\Temp\pip-install-6hj9rjyr\scalene_09d2c173db09414b8ea4502001e4918f\
    Complete output (3 lines):
    running egg_info
    make vendor-deps
    error: command 'make' failed: None
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e8/35/a125f8ecacfce3b9be9c712bd6d9bd514aed798857cc7330c89d2df7db58/scalene-1.3.16.tar.gz#sha256=3c2fb524b4c611773b147dc889e2d58b48a543d3161ea576ccc0db778e9f5915 (from https://pypi.org/simple/scalene/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached scalene-1.3.15.tar.gz (2.9 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Yano\miniconda3\envs\scalene\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yano\\AppData\\Local\\Temp\\pip-install-6hj9rjyr\\scalene_bd5535cfb37a4bdc908d92fc96aacc7e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yano\\AppData\\Local\\Temp\\pip-install-6hj9rjyr\\scalene_bd5535cfb37a4bdc908d92fc96aacc7e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Yano\AppData\Local\Temp\pip-pip-egg-info-2433zbu0'
         cwd: C:\Users\Yano\AppData\Local\Temp\pip-install-6hj9rjyr\scalene_bd5535cfb37a4bdc908d92fc96aacc7e\
    Complete output (3 lines):
    running egg_info
    make vendor-deps
    error: command 'make' failed: None
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/63/6e/eddceea4dc588b99af48607b8133b40fc155a27d1ac7351f570f8d7cf6f6/scalene-1.3.15.tar.gz#sha256=0b3f8aa56d6320f8071f8135b422e8cf51b51de2947aec75c76c1ea3abf61c12 (from https://pypi.org/simple/scalene/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached scalene-1.3.12-cp38-abi3-win_amd64.whl (58 kB)
Collecting cloudpickle>=1.5.0
  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Collecting nvidia-ml-py==11.450.51
  Using cached nvidia-ml-py-11.450.51.tar.gz (23 kB)
Collecting rich>=9.2.10
  Downloading rich-10.16.1-py3-none-any.whl (214 kB)
     |████████████████████████████████| 214 kB 437 kB/s
Collecting numpy
  Downloading numpy-1.21.4-cp39-cp39-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 3.3 MB/s
Collecting colorama<0.5.0,>=0.4.0
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.10.0-py3-none-any.whl (1.0 MB)
Building wheels for collected packages: nvidia-ml-py
  Building wheel for nvidia-ml-py (setup.py) ... done
  Created wheel for nvidia-ml-py: filename=nvidia_ml_py-11.450.51-py3-none-any.whl size=24234 sha256=504466a678fc5fffde5565c4920d68808465b6fa657068a8f22ca5e020c62cea
  Stored in directory: c:\users\yano\appdata\local\pip\cache\wheels\23\e5\db\ea23c5de5290f7d69ad98d98e7aab847e83a2e70d971f502ca
Successfully built nvidia-ml-py
Installing collected packages: pygments, commonmark, colorama, rich, nvidia-ml-py, numpy, cloudpickle, scalene
Successfully installed cloudpickle-2.0.0 colorama-0.4.4 commonmark-0.9.1 numpy-1.21.4 nvidia-ml-py-11.450.51 pygments-2.10.0 rich-10.16.1 scalene-1.3.12
`````

I get the following error on scalene 1.3.12:
``````````
(scalene) C:\Users\Yano>scalene test.py
Error in program being profiled:
 Unknown Error
Traceback (most recent call last):
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "test.py", line 3, in <module>
    time.sleep((i & 10) / 100)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
Scalene: An exception of type NVMLError_Unknown occurred. Arguments:
(999,)
ERROR: Calling scalene main function failed: Unknown Error
Traceback (most recent call last):
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "test.py", line 3, in <module>
    time.sleep((i & 10) / 100)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 1992, in nvmlDeviceGetUtilizationRates
    ret = fn(handle, byref(c_util))
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1201, in profile_code
    exec(code, the_globals, the_locals)
  File "test.py", line 3, in <module>
    time.sleep((i & 10) / 100)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 1992, in nvmlDeviceGetUtilizationRates
    ret = fn(handle, byref(c_util))
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1320, in run_profiler
    exit_status = profiler.profile_code(
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1207, in profile_code
    traceback.print_exc()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1334, in run_profiler
    print(traceback.format_exc())
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 366, in extract
    f.line
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\tokenize.py", line 363, in detect_encoding
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\tokenize.py", line 321, in read_or_stop
    return readline()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 505, in cpu_signal_handler
    gpu_load = Scalene.__gpu.load()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_gpu.py", line 37, in load
    l += pynvml.nvmlDeviceGetUtilizationRates(self.__handle[i]).gpu
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 1993, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\pynvml.py", line 697, in _nvmlCheckReturn
    raise NVMLError(ret)pynvml.NVMLError_Unknown: Unknown Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\__main__.py", line 7, in main
    scalene_profiler.Scalene.main()
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1241, in main
    Scalene.run_profiler(args, left)
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\site-packages\scalene\scalene_profiler.py", line 1343, in run_profiler
      File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 366, in extract
    f.line
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\traceback.py", line 288, in line


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Yano\miniconda3\envs\scalene\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yano\miniconda3\envs\scalene\Scripts\scalene.exe\__main__.py", line 7, in <module>
``````````

test.py
`````
import time
for i in range(10000):
    time.sleep((i & 10) / 100)
`````

**Comment by danielhrisca** [comment]
I see the same error on my Windows 10 and Python 3.9.9 x64

**Comment by emeryberger** [comment]
Just installed and tested some Windows-specific fixes - please try again by installing from the repository:

`python3 -m pip install git+https://github.com/plasma-umass/scalene`

**Comment by ywilke** [comment]
Thank you! Version 1.3.16 now installs.
