### ISSUE TITLE
When using multiprocessing Manager: ``Can't pickle local object 'replacement_lock.<locals>.ReplacementLock'``

### ISSUE THREAD

**Issue by ywilke** [plasma-umass/scalene#308]
**Describe the bug**
When trying to create a Manager with ``multiprocessing.Manager()`` I get the following error ``Can't pickle local object 'replacement_lock.<locals>.ReplacementLock``

**To Reproduce**
1. Create fresh environment with conda and python 3.9.7
2. Install scalene with pip from GitHub. Latest commit at the time of writing is ``58c2d9794cedfc5147880270d25a68106e6bb62e``.
3. Try to profile a script that creates a manger from multiprocessing.

**Expected behavior**
The script would be profiled. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Stackstrace:

``````
(my_project) C:\Users\Username\PycharmProjects\my_project>scalene scalene_test.py
Error in program being profiled:
 Can't pickle local object 'replacement_lock.<locals>.ReplacementLock'
Traceback (most recent call last):
  File "C:\Users\Username\miniconda3\envs\my_project\lib\site-packages\scalene\scalene_profiler.py", line 1394, in profile_code
    exec(code, the_globals, the_locals)
  File "scalene_test.py", line 2, in <module>
    m = multiprocessing.Manager()
  File "C:\Users\Username\miniconda3\envs\my_project\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Users\Username\miniconda3\envs\my_project\lib\multiprocessing\managers.py", line 554, in start
    self._process.start()
  File "C:\Users\Username\miniconda3\envs\my_project\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Username\miniconda3\envs\my_project\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
Python path configuration:
  File "C:\Users\Username\miniconda3\envs\my_project\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  PYTHONHOME =   File "C:\Users\Username\miniconda3\envs\my_project\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
(not set)AttributeError: Can't pickle local object 'replacement_lock.<locals>.ReplacementLock'

  PYTHONPATH = (not set)
  program name = 'pythoScalene: Program did not run for long enough to profile.n
.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\Username\\miniconda3\\envs\\my_project\\python.exe'
  sys.base_prefix = 'C:\\Users\\Username\\miniconda3\\envs\\my_project'
  sys.base_exec_prefix = 'C:\\Users\\Username\\miniconda3\\envs\\my_project'
  sys.platlibdir = 'lib'
  sys.executable = 'python.exe'
  sys.prefix = 'C:\\Users\\Username\\miniconda3\\envs\\my_project'
  sys.exec_prefix = 'C:\\Users\\Username\\miniconda3\\envs\\my_project'
  sys.path = [
    'C:\\Users\\Username\\miniconda3\\envs\\my_project\\python39.zip',
    '.\\DLLs',
    '.\\lib',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000728 (most recent call first):
<no Python frame>
``````
scalene_test.py:

```
import multiprocessing
m = multiprocessing.Manager()
```

**Comment by sternj** [comment]
Confirming that manager works (preliminarily) as expected; closing in 72-ish hours

**Comment by emeryberger** [comment]
Should be fixed by https://github.com/plasma-umass/scalene/commit/5e6982e49d0bacc084ec324fa9649b1192cc3593
