### ISSUE TITLE
Scalene won't run on Mac M1 and MacPorts' Python: ImportError and incompatible architecture

### ISSUE THREAD

**Issue by abey79** [plasma-umass/scalene#331]
**Describe the bug**
 
I get this error when trying to use scalene:

```
$ scalene test.py
Traceback (most recent call last):
  File "/private/tmp/venv/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/private/tmp/venv/lib/python3.9/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/private/tmp/venv/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 46, in <module>
    from scalene.scalene_mapfile import ScaleneMapFile
  File "/private/tmp/venv/lib/python3.9/site-packages/scalene/scalene_mapfile.py", line 6, in <module>
    from scalene import get_line_atomic  # type: ignore
ImportError: dlopen(/private/tmp/venv/lib/python3.9/site-packages/scalene/get_line_atomic.abi3.so, 0x0002): tried: '/private/tmp/venv/lib/python3.9/site-packages/scalene/get_line_atomic.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/get_line_atomic.abi3.so' (no such file), '/usr/lib/get_line_atomic.abi3.so' (no such file)
```

**To Reproduce**

```bash
$ cat test.py
tot = 0
for i in range(1000000):
   tot += i

print(tot)

$ python -m venv venv
$ source venv/bin/activate
(venv) $ pip install scalene
Collecting scalene
  Using cached scalene-1.4.0-cp39-cp39-macosx_10_14_universal2.whl (93 kB)
Collecting cloudpickle>=1.5.0
  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Collecting rich>=9.2.0
  Using cached rich-11.0.0-py3-none-any.whl (215 kB)
Collecting numpy
  Using cached numpy-1.22.1-cp39-cp39-macosx_11_0_arm64.whl (12.8 MB)
Collecting nvidia-ml-py>=11.450.51
  Using cached nvidia-ml-py-375.53.tar.gz (22 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/8c/63/cd93f1cdaf93c3e4aa1827373492d74de5c58af3613ba1eb3dd5c01f4128/nvidia-ml-py-375.53.tar.gz#sha256=0167a6acff2cb8b21195685da1c4e862c73c5201d06e36f48d5eeb9d1868e28f (from https://pypi.org/simple/nvidia-ml-py/). Requested nvidia-ml-py>=11.450.51 from https://files.pythonhosted.org/packages/8c/63/cd93f1cdaf93c3e4aa1827373492d74de5c58af3613ba1eb3dd5c01f4128/nvidia-ml-py-375.53.tar.gz#sha256=0167a6acff2cb8b21195685da1c4e862c73c5201d06e36f48d5eeb9d1868e28f (from scalene) has inconsistent version: filename has '375.53', but metadata has '375.53.1'
  Using cached nvidia_ml_py-11.515.0-py3-none-any.whl (28 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting colorama<0.5.0,>=0.4.0
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Installing collected packages: pygments, commonmark, colorama, rich, nvidia-ml-py, numpy, cloudpickle, scalene
Successfully installed cloudpickle-2.0.0 colorama-0.4.4 commonmark-0.9.1 numpy-1.22.1 nvidia-ml-py-11.515.0 pygments-2.11.2 rich-11.0.0 scalene-1.4.0
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/private/tmp/venv/bin/python -m pip install --upgrade pip' command.

(venv) $ scalene test.py
Traceback (most recent call last):
  File "/private/tmp/venv/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/private/tmp/venv/lib/python3.9/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/private/tmp/venv/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 46, in <module>
    from scalene.scalene_mapfile import ScaleneMapFile
  File "/private/tmp/venv/lib/python3.9/site-packages/scalene/scalene_mapfile.py", line 6, in <module>
    from scalene import get_line_atomic  # type: ignore
ImportError: dlopen(/private/tmp/venv/lib/python3.9/site-packages/scalene/get_line_atomic.abi3.so, 0x0002): tried: '/private/tmp/venv/lib/python3.9/site-packages/scalene/get_line_atomic.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/get_line_atomic.abi3.so' (no such file), '/usr/lib/get_line_atomic.abi3.so' (no such file)
```

**Desktop (please complete the following information):**
 - MacBook Pro M1 Max 2021
 - OS: Monterey 12.1
 - Python 3.9.10 installed with MacPorts

**Comment by emeryberger** [comment]
Cannot reproduce (runs fine for me, M1, same OS, 3.9.9). I don't use MacPorts, though - installed Python from Python.org, IIRC.

**Comment by abey79** [comment]
Indeed, it works with the official Python 3.9.9 for me too. I'll try to dig a bit more into it and see what different I can find between the two installs.

**Comment by emeryberger** [comment]
OK, closing for now. If you have any more info, please let us know!

**Comment by Mark90** [comment]
Hi, hope it's alright to bump an old issue.

I was interested in trying out scalene but in Python 3.10 I'm seeing the same error as in the starting post.

Hardware/software:
* MacBook Pro M1 2020
* OS: Monterey 12.5.1
* Python 3.10.6 (installed/compiled with [pyenv](https://github.com/pyenv/pyenv))

Example:
```
Ξ ~ → pyenv virtualenv 3.10.6 310-scalene
Ξ ~ → pyenv activate 310-scalene
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(310-scalene) Ξ ~ → pip install -U pip
Requirement already satisfied: pip in ./.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages (22.2.1)
Collecting pip
  Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 15.8 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.1
    Uninstalling pip-22.2.1:
      Successfully uninstalled pip-22.2.1
Successfully installed pip-22.2.2
(310-scalene) Ξ ~ → pip install scalene
Collecting scalene
  Using cached scalene-1.5.10-cp310-cp310-macosx_10_15_universal2.whl (358 kB)
Collecting rich>=9.2.0
  Downloading rich-12.5.1-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 kB 3.8 MB/s eta 0:00:00
Collecting cloudpickle>=1.5.0
  Downloading cloudpickle-2.1.0-py3-none-any.whl (25 kB)
Collecting pynvml>=11.0.0
  Downloading pynvml-11.4.1-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB 1.7 MB/s eta 0:00:00
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.4 MB/s eta 0:00:00
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 kB 2.1 MB/s eta 0:00:00
Installing collected packages: commonmark, pynvml, pygments, cloudpickle, rich, scalene
Successfully installed cloudpickle-2.1.0 commonmark-0.9.1 pygments-2.13.0 pynvml-11.4.1 rich-12.5.1 scalene-1.5.10
(310-scalene) Ξ ~ →
(310-scalene) Ξ ~ → python
Python 3.10.6 (main, Aug 22 2022, 11:44:01) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scalene
>>>
(310-scalene) Ξ ~ → python main.py
Never going to give you up
^CTraceback (most recent call last):
  File "/Users/mark/main.py", line 9, in <module>
    loop()
  File "/Users/mark/main.py", line 6, in loop
    time.sleep(3)
KeyboardInterrupt

(310-scalene) ↑130 ~ →
(310-scalene) ↑130 ~ → scalene main.py
Traceback (most recent call last):
  File "/Users/mark/.pyenv/versions/310-scalene/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/Users/mark/.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/Users/mark/.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 48, in <module>
    from scalene.scalene_mapfile import ScaleneMapFile
  File "/Users/mark/.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages/scalene/scalene_mapfile.py", line 7, in <module>
    from scalene import get_line_atomic  # type: ignore
ImportError: dlopen(/Users/mark/.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages/scalene/get_line_atomic.abi3.so, 0x0002): tried: '/Users/mark/.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages/scalene/get_line_atomic.abi3.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

Importing scalene from a 3.10 interpreter works, but I can't run it as executable.

The .so file mentioned in the Traceback is indeed an x86_64 one:


> (310-scalene) ↑1 ~ → file /Users/mark/.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages/scalene/get_line_atomic.abi3.so
/Users/mark/.pyenv/versions/3.10.6/envs/310-scalene/lib/python3.10/site-packages/scalene/get_line_atomic.abi3.so: Mach-O 64-bit bundle x86_64


Any idea what this could be?

**Comment by klaventall** [comment]
hello. am having the same issue as Mark90. 

Hardware/software:

MacBook Pro M1 2020
OS: Monterey 12.5.1
Python 3.8.13

```
Traceback (most recent call last):
  File "/Users/kwurman/.virtualenvs/bae/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/Users/kwurman/.virtualenvs/bae/lib/python3.10/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/Users/kwurman/.virtualenvs/bae/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 48, in <module>
    from scalene.scalene_mapfile import ScaleneMapFile
  File "/Users/kwurman/.virtualenvs/bae/lib/python3.10/site-packages/scalene/scalene_mapfile.py", line 7, in <module>
    from scalene import get_line_atomic  # type: ignore
ImportError: dlopen(/Users/kwurman/.virtualenvs/bae/lib/python3.10/site-packages/scalene/get_line_atomic.abi3.so, 0x0002): tried: '/Users/kwurman/.virtualenvs/bae/lib/python3.10/site-packages/scalene/get_line_atomic.abi3.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by jaltmayerpizzorno** [comment]
@Mark90 @klaventall Thanks for letting us know.  We'll be making a new release shortly that fixes that issue. You can work around it by building from source, or by using this test build I just uploaded: https://test.pypi.org/project/scalene/1.5.10.dev202209091442/ .

**Comment by jaltmayerpizzorno** [comment]
The release is up (1.5.11).
