### ISSUE TITLE
TypeError: replacement_get_context() missing 1 required positional argument: 'method'

### ISSUE THREAD

**Issue by kdebrab** [plasma-umass/scalene#336]
Trying out scalene with a (long) script that uses joblib.Parallel (as part of scikit-learn neareast neighbors regression), the script fails with:

```
[...]
File "/usr/local/lib/python3.9/site-packages/sklearn/neighbors/_regression.py", line 229, in predict
neigh_dist, neigh_ind = self.kneighbors(X)
File "/usr/local/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 776, in kneighbors
chunked_results = Parallel(n_jobs, **parallel_kwargs)(
File "/usr/local/lib/python3.9/site-packages/joblib/parallel.py", line 676, in __init__
self._backend_args['context'] = mp.get_context()
TypeError: replacement_get_context() missing 1 required positional argument: 'method'
```

This is not a minimal reproducible example, but I'd guess it has something to do with `replacement_get_context` in https://github.com/plasma-umass/scalene/blob/master/scalene/replacement_get_context.py (with the required argument 'method'), defined as a replacement of `multiprocessing.get_context` (where the argument 'method' is optional)?

FWIW, disabling joblib mulitprocessing by setting the environment variable `JOBLIB_MULTIPROCESSING` to 0 proved to be a workaround.

## versions
scalene: 1.4.2
joblib: 1.1.0
python: 3.9
OS: linux

**Comment by sternj** [comment]
Would you be able to check that the most recent commit fixes the issue? If you did not build from source, you can install with `pip install git+https://github.com/plasma-umass/scalene`.

**Comment by kdebrab** [comment]
Thanks for the quick response.

Testing the fix from my windows laptop (where I had exactly the same error as in the linux docker image), I get now another error:
```
  File "c:\python39\lib\site-packages\sklearn\neighbors\_regression.py", line 229, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "c:\python39\lib\site-packages\sklearn\neighbors\_base.py", line 776, in kneighbors
    chunked_results = Parallel(n_jobs, **parallel_kwargs)(
  File "c:\python39\lib\site-packages\joblib\parallel.py", line 674, in __init__
    self._backend_args['context'] = mp.get_context()
  File "c:\python39\lib\site-packages\scalene\replacement_get_context.py", line 9, in replacement_get_context
    return old_get_context('fork')
  File "c:\python39\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "c:\python39\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

**Comment by kdebrab** [comment]
A minimum reproducible example:

```python
from math import sqrt
from joblib import Parallel, delayed


def main():
    Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(10))


main()
```
which produces the following traceback (after the fix):
```
Error in program being profiled:
 cannot find context for 'fork'
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\scalene\scalene_profiler.py", line 1406, in profile_code
    exec(code, the_globals, the_locals)
  File "eee\solar\healthscan\try_scalene.py", line 12, in <module>
    main()
  File "eee\solar\healthscan\try_scalene.py", line 9, in main
    Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(10))
  File "c:\python39\lib\site-packages\joblib\parallel.py", line 674, in __init__    self._backend_args['context'] = mp.get_context()
  File "c:\python39\lib\site-packages\scalene\replacement_get_context.py", line 9, in replacement_get_context
    return old_get_context('fork')
  File "c:\python39\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "c:\python39\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

**Comment by sternj** [comment]
Ah, we don't support multiprocess profiling on Windows at all. I will put a
guard around that! Please try again on a Linux or Mac instance.

**Comment by kdebrab** [comment]
I tried on Linux and there indeed it worked! Thanks for the quick resolution.

**Comment by sternj** [comment]
Closing the issue! @kdebrab please let us know if Scalene proves useful to you!

**Comment by kdebrab** [comment]
@sternj What really looks enticing are the memory profiling, native/python split-up and copying stats, but, unfortunately, I didn't get that working yet, see #337. It does work though with the same script on my windows laptop, but the CPU profiling doesn't reveal that much.
