### ISSUE TITLE
Encoding is not correct (using utf-8) on Windows10 , get UnicodeDecodeError

### ISSUE THREAD

**Issue by victor23d** [plasma-umass/scalene#339]
**Describe the bug**
Encoding is not correct (using utf-8) on Windows10 , get UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 1022: illegal multibyte sequence

**To Reproduce**
`scalene.exe a.py`
in a.py:
```
    import locale
    print(locale.getpreferredencoding())
```
output:
` cp936 `

in the codebase include characters other than utf-8, such as GBK, will got error:
``` Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.1\lib\site-packages\scalene\scalene_profiler.py", line 1606, in run_profiler
    exit_status = profiler.profile_code(
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.1\lib\site-packages\scalene\scalene_profiler.py", line 1439, in profile_code
    if not Scalene.output_profile():
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.1\lib\site-packages\scalene\scalene_profiler.py", line 652, in output_profile
    json_output = Scalene.__json.output_profiles(
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.1\lib\site-packages\scalene\scalene_json.py", line 240, in output_profiles
    code_lines = source_file.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 1022: illegal multibyte sequence
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version scalene 1.5.1

**Comment by W4nde3** [comment]
The same problem also occurs at line 538 of scalene_output.py, which is problematic when used like this
`python3 -m scalene --cli .\core.py`

```
Traceback (most recent call last):
  File "I:\code\python\python3.8.8\lib\site-packages\scalene\scalene_profiler.py", line 1606, in run_profiler
    exit_status = profiler.profile_code(
  File "I:\code\python\python3.8.8\lib\site-packages\scalene\scalene_profiler.py", line 1439, in profile_code
    if not Scalene.output_profile():
  File "I:\code\python\python3.8.8\lib\site-packages\scalene\scalene_profiler.py", line 686, in output_profile
    did_output: bool = output.output_profiles(
  File "I:\code\python\python3.8.8\lib\site-packages\scalene\scalene_output.py", line 541, in output_profiles
    code_lines = source_file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 1737: illegal multibyte sequence
```

**Comment by W4nde3** [comment]
@victor23d Could you please fix this problem?

**Comment by emeryberger** [comment]
I just pushed a release (1.5.3) that includes this fix. Hopefully this solves your problem.

**Comment by Zhu-Aemon** [comment]
@emeryberger Hi. sorry to bother you. I encountered this problem again with the latest Scalene version 1.5.49 (2024.12.03). My code is very simple:
```
import pandas as pd
import pymongo
from scalene import scalene_profiler

scalene_profiler.start()

mongo = pymongo.MongoClient("mongodb://localhost:27017/")
data = pd.DataFrame(mongo['stock']['em_users_detail'].find({}, {'user_id': 1}).limit(1000000))

scalene_profiler.stop()
```
I run scalene from command line using `scalene test.py`. It gave me the same error:
```
Traceback (most recent call last):
  File "E:\PyCharmProjects\XXT\.venv\lib\site-packages\scalene\scalene_profiler.py", line 2132, in run_profiler
    exit_status = profiler.profile_code(
  File "E:\PyCharmProjects\XXT\.venv\lib\site-packages\scalene\scalene_profiler.py", line 1850, in profile_code
    generate_html(
  File "E:\PyCharmProjects\XXT\.venv\lib\site-packages\scalene\scalene_utility.py", line 128, in generate_html
    "scalene_gui_js_text": read_file_content(
  File "E:\PyCharmProjects\XXT\.venv\lib\site-packages\scalene\scalene_utility.py", line 113, in read_file_content
    return pathlib.Path(file_path).read_text()
  File "C:\Users\sersmile\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1267, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 298448: illegal multibyte sequence

NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization.
If you have sudo privileges, you can run this command (Linux only) to enable per-process GPU accounting:
  python3 -m scalene.set_nvidia_gpu_modes
```
I thought this is related to my program at first. So I tested scalene out with a simple program and got the same error:
```
tmp = 1

for i in range(10000000):
    tmp += 1
```
It is strange. I don't know much about encodings. But it seems to me that `gbk` is related to Chinese characters. But there is no Chinese character in my program. Does it have something to do with me being Chinese? 

However, after I changed my Windows region setting to US and my PC language to English and reboot the system. The problem persists. Could you figure out a fix?
