### ISSUE TITLE
AttributeError: 'str' object has no attribute '__name__'

### ISSUE THREAD

**Issue by laplasz** [plasma-umass/scalene#366]
**Describe the bug**
during execution:
```
Error in program being profiled:
 'str' object has no attribute '__name__'
Scalene failed to initialize.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 1359, in run_profiler
    code, the_locals, the_globals
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 1255, in profile_code
    reduced_profile=Scalene.__args.reduced_profile,
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_output.py", line 628, in output_profiles
    console.print(tbl)
  File "/usr/lib/python3.6/site-packages/rich/console.py", line 1637, in print
    self._buffer.extend(new_segments)
  File "/usr/lib/python3.6/site-packages/rich/console.py", line 837, in __exit__
    self._exit_buffer()
  File "/usr/lib/python3.6/site-packages/rich/console.py", line 795, in _exit_buffer
    self._check_buffer()
  File "/usr/lib/python3.6/site-packages/rich/console.py", line 1929, in _check_buffer
    self.file.write(text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 448-453: ordinal not in range(128)
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 1368, in run_profiler
    print(message)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 1237, in profile_code
    exec(code, the_globals, the_locals)
  File "backendselector.py", line 8, in <module>
    from lbmaineventhandler import LbMainEventHandler
  File "/opt/lb/lbmaineventhandler.py", line 7, in <module>
    from eventlisteners import (
  File "/opt/lb/eventlisteners.py", line 13, in <module>
    import firewallmanagement_pb2_grpc
  File "/opt/lb/firewallmanagement_pb2_grpc.py", line 5, in <module>
    import grpc
  File "/usr/lib64/python3.6/site-packages/grpc/__init__.py", line 228, in <module>
    class StatusCode(enum.Enum):
  File "/usr/lib64/python3.6/enum.py", line 135, in __new__
    enum_members = {k: classdict[k] for k in classdict._member_names}
  File "/usr/lib64/python3.6/enum.py", line 135, in <dictcomp>
    enum_members = {k: classdict[k] for k in classdict._member_names}
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 490, in cpu_signal_handler
    Scalene.cpu_signal_handler_helper(signum, this_frame)
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 606, in cpu_signal_handler_helper
UnicodeEncodeError: 'ascii' codec can't encode characters in position 559-564: ordinal not in range(128)

    Scalene.enter_function_meta(frame, Scalene.__stats)
  File "/usr/lib64/python3.6/site-packages/scalene/scalene_profiler.py", line 777, in enter_function_meta
    prepend_name = f.f_locals["cls"].__name__
AttributeError: 'str' object has no attribute '__name__'
```

**Desktop (please complete the following information):**
 - OS: linux
 - Version 1.3.4.7

**Comment by sternj** [comment]
We do not support any Python versions before 3.8. Closing this issue, please reopen if you upgrade and have the same issue.

**Comment by sternj** [comment]
We do not provide support for any previous versions of Scalene, you are more than welcome to experiment on your own.
