### ISSUE TITLE
installation error: ModuleNotFoundError: No module named 'wheel'

### ISSUE THREAD

**Issue by laplasz** [plasma-umass/scalene#367]
**Describe the bug**
got this error during `pip3.9 install scalene`
```
#21 4.805 Collecting scalene
#21 4.847   Downloading scalene-1.5.4.tar.gz (4.0 MB)
#21 5.115     ERROR: Command errored out with exit status 1:
#21 5.115      command: /usr/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-896mx6hu/scalene/setup.py'"'"'; __file__='"'"'/tmp/pip-install-896mx6hu/scalene/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xt82w_s3
#21 5.115          cwd: /tmp/pip-install-896mx6hu/scalene/
#21 5.115     Complete output (5 lines):
#21 5.115     Traceback (most recent call last):
#21 5.115       File "<string>", line 1, in <module>
#21 5.115       File "/tmp/pip-install-896mx6hu/scalene/setup.py", line 71, in <module>
#21 5.115         from wheel.bdist_wheel import bdist_wheel as orig_bdist_wheel
#21 5.115     ModuleNotFoundError: No module named 'wheel'
#21 5.115     ----------------------------------------
#21 5.115 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Desktop (please complete the following information):**
 - OS: Suse Linux
 - Version: 1.5.4

**Additional context**
python39 and python39-pip  package installed.
pip setuptools version is 44.1.1

**Comment by JCrane512** [comment]
pip install wheel

**Comment by laplasz** [comment]
thanks for the quick answer but unfortunately it did not help when installed wheel.

**Comment by JCrane512** [comment]
Did you get the same error?

Are you using a python virtual environment?

What do you get from $ pip list?

**Comment by laplasz** [comment]
i think python3-devel and python39-devel were needed as well.
finally it installed - thanks for the help!
