### ISSUE TITLE
pynvml - SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)

### ISSUE THREAD

**Issue by laplasz** [plasma-umass/scalene#369]
**Describe the bug**
right after starting scalene there is an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/usr/local/lib64/python3.9/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/usr/local/lib64/python3.9/site-packages/scalene/scalene_profiler.py", line 65, in <module>
    from scalene.scalene_gpu import ScaleneGPU
  File "/usr/local/lib64/python3.9/site-packages/scalene/scalene_gpu.py", line 3, in <module>
    import pynvml
  File "/usr/local/lib/python3.9/site-packages/pynvml.py", line 1831
    print c_count.value
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)?

```

**Desktop (please complete the following information):**
 - OS: linux
 - Version: v1.5.4

**Comment by emeryberger** [comment]
This is a pynvml problem (see https://github.com/plasma-umass/scalene/issues/358). The repo version resolves this - please install from the repo (`python3 -m pip install -U git+https://github.com/plasma-umass/scalene`) and let us know if it works. Thanks!

**Comment by laplasz** [comment]
unfortunately the result is the same - anything else I can do with this issue @emeryberger ? Thanks in advance!
```
 python3.9 -m pip install -U git+https://github.com/plasma-umass/scalene
Collecting git+https://github.com/plasma-umass/scalene
  Cloning https://github.com/plasma-umass/scalene to /tmp/pip-req-build-bvgpir7f
Requirement already satisfied, skipping upgrade: cloudpickle>=1.5.0 in /usr/local/lib/python3.9/site-packages (from scalene==1.5.4) (2.0.0)
Requirement already satisfied, skipping upgrade: numpy in /usr/local/lib64/python3.9/site-packages (from scalene==1.5.4) (1.22.2)
Requirement already satisfied, skipping upgrade: nvidia-ml-py!=375.53,>=11.450.51 in /usr/local/lib/python3.9/site-packages (from scalene==1.5.4) (375.53.1)
Requirement already satisfied, skipping upgrade: rich>=9.2.0 in /usr/local/lib/python3.9/site-packages (from scalene==1.5.4) (11.2.0)
Requirement already satisfied, skipping upgrade: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.9/site-packages (from rich>=9.2.0->scalene==1.5.4) (0.4.4)
Requirement already satisfied, skipping upgrade: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.9/site-packages (from rich>=9.2.0->scalene==1.5.4) (0.9.1)
Requirement already satisfied, skipping upgrade: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.9/site-packages (from rich>=9.2.0->scalene==1.5.4) (2.11.2)
Building wheels for collected packages: scalene
  Building wheel for scalene (setup.py) ... done
  Created wheel for scalene: filename=scalene-1.5.4-cp39-cp39-linux_x86_64.whl size=633813 sha256=89f19ebb5c34982c6034e455e970299f24c3dcfd99c4cad0853bdd08b73950a4
  Stored in directory: /tmp/pip-ephem-wheel-cache-_4a6pzsa/wheels/b5/9a/6b/99f8971bd588f69b6774efcd6235b5c3297253f66d396e1fb5
Successfully built scalene
Installing collected packages: scalene
Successfully installed scalene-1.5.4
6243a8f8af7b:/ # cd /opt/lb/            
6243a8f8af7b:/opt/lb # scalene --reduced-profile --profile-all --outfile /logs/memory backendselector.py
Traceback (most recent call last):
  File "/usr/local/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/usr/local/lib64/python3.9/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/usr/local/lib64/python3.9/site-packages/scalene/scalene_profiler.py", line 65, in <module>
    from scalene.scalene_gpu import ScaleneGPU  # type: ignore
  File "/usr/local/lib64/python3.9/site-packages/scalene/scalene_gpu.py", line 4, in <module>
    import pynvml
  File "/usr/local/lib/python3.9/site-packages/pynvml.py", line 1831
    print c_count.value
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)?
```

**Comment by emeryberger** [comment]
The problem is an old version of pynvml, presumably not the one we have already blocked. Can you do the following? Let me know what ` python3 -m pip show pynvml` says, and then go ahead and update it (`python3 -m pip install -U pynvml`). If the latter doesn't work, do the pip show again and in any event, please let us know. Thanks!

**Comment by laplasz** [comment]
```
6243a8f8af7b:/opt/lb # python3.9 -m pip show pynvml
WARNING: Package(s) not found: pynvml
6243a8f8af7b:/opt/lb # python3.9 -m pip install -U pynvml
Collecting pynvml
  Downloading pynvml-11.4.1-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 15.0 MB/s 
Installing collected packages: pynvml
Successfully installed pynvml-11.4.1
```
After that there is no more initial error when starting! Thanks a lot hope this time it will work.
If you dont have comments on this - please close the ticket.. thanks again!

**Comment by emeryberger** [comment]
Weird that it didn't find it the first time, too bad! I think we should probably just enforce a version >= 11 - thanks!
