### ISSUE TITLE
Scalene does not work with ray

### ISSUE THREAD

**Issue by AdityaGudimella** [plasma-umass/scalene#402]
**Describe the bug**
[ray](https://github.com/ray-project/ray) crashes when invoked with scalene

**To Reproduce**
Run the following code with scalene

```python
import ray
ray.init()
```

and invoke it with scalene:
`python -m scalene script.py`

**Expected behavior**
I should see this log:
`INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265`
Instead, I see the following logs:
```
2022-06-10 05:55:24,844 ERROR services.py:1474 -- Failed to start the dashboard: Failed to start the dashboard, return code 2
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'
2022-06-10 05:55:24,844 ERROR services.py:1475 -- Failed to start the dashboard, return code 2
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'
Traceback (most recent call last):
  File ".../python3.9/site-packages/ray/_private/services.py", line 1437, in start_dashboard
    with open(dashboard_log, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../python3.9/site-packages/ray/_private/services.py", line 1448, in start_dashboard
    raise Exception(err_msg + f"\nFailed to read dashboard log: {e}")
Exception: Failed to start the dashboard, return code 2
Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'
[2022-06-10 05:55:36,144 E 1500916 1500916] core_worker.cc:137: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser NA
 - Version 20.04

**Additional context**
NA

**Comment by emeryberger** [comment]
Thanks for the bug report. Reproduced locally.

**Comment by chengzi0103** [comment]
> **Describe the bug** [ray](https://github.com/ray-project/ray) crashes when invoked with scalene
> 
> **To Reproduce** Steps to reproduce the behavior: Run the following code with scalene
> 
> ```python
> import ray
> ray.init()
> ```
> 
> and invoke it with scalene: `python -m scalene script.py`
> 
> **Expected behavior** I should see this log: `INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265` Instead, I see the following logs:
> 
> ```
> 2022-06-10 05:55:24,844 ERROR services.py:1474 -- Failed to start the dashboard: Failed to start the dashboard, return code 2
> Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'
> 2022-06-10 05:55:24,844 ERROR services.py:1475 -- Failed to start the dashboard, return code 2
> Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'
> Traceback (most recent call last):
>   File ".../python3.9/site-packages/ray/_private/services.py", line 1437, in start_dashboard
>     with open(dashboard_log, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".../python3.9/site-packages/ray/_private/services.py", line 1448, in start_dashboard
>     raise Exception(err_msg + f"\nFailed to read dashboard log: {e}")
> Exception: Failed to start the dashboard, return code 2
> Failed to read dashboard log: [Errno 2] No such file or directory: '/tmp/ray/session_2022-06-10_05-55-22_308871_1500916/logs/dashboard.log'
> [2022-06-10 05:55:36,144 E 1500916 1500916] core_worker.cc:137: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
> ```
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 20.04
> * Browser NA
> * Version 20.04
> 
> **Additional context** ray version: 1.12.1

hello  , 
I'm also trying to get the sys-infomation of the remote function from ray, do you have a better way to collect it?

**Comment by crides** [comment]
Hi, I'm also trying to use scalene to profile a ray application. Unlike posted above, it doesn't produce any errors, but just hangs instead, not starting any workers. I'm simply using ray with:

```python
ray.init()
```

after which ray reports:

```
2023-01-08 15:36:36,724 INFO worker.py:1538 -- Started a local Ray instance.
```

and then hangs.

I'm using a fairly recently upgraded Arch, with python 3.8.15, using ray 2.2.0 (without any addons, just the core) and scalene 1.5.19.

**Comment by udit7395** [comment]
Facing similar behavior as @crides user above on scalene [v1.5.39](https://github.com/plasma-umass/scalene/releases/tag/v1.5.39)

 @emeryberger @sternj Could you please share an update on this?
