### ISSUE TITLE
crash after install: 'raise_signal' bug

### ISSUE THREAD

**Issue by pythonmobile** [plasma-umass/scalene#407]
**Describe the bug**

```
scalene ./load_data.py
Traceback (most recent call last):
  File "/home/uname/python/bin/scalene", line 5, in <module>
    from scalene.__main__ import main
  File "/home/uname/python/lib/python3.7/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/home/uname/python/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 105, in <module>
    class Scalene:
  File "/home/uname/python/lib/python3.7/site-packages/scalene/scalene_profiler.py", line 201, in Scalene
    __orig_raise_signal = signal.raise_signal
AttributeError: module 'signal' has no attribute 'raise_signal'
```

**To Reproduce**

Just pip install scalene and run it on a file on 

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

Python 3.7.0

**Expected behavior**
Should have profiled the code.

**Comment by emeryberger** [comment]
Scalene does not support Python versions < 3.8; I suspect `pip` is just trying to install an old version that wasn't marked as incompatible.

**Comment by SnoopJ** [comment]
I just ran into this, with `1.5.4`, which was the last release marked as compatible with 3.7. Seems like a bug in that release, downgrading to `1.5.3` fixed the issue for me.
