### ISSUE TITLE
Scalene incompatible with Numba parallel=True on Windows

### ISSUE THREAD

**Issue by replicaacliper** [plasma-umass/scalene#416]
Hi, thanks for the great tool. It's been extremely useful in improving my code's performance.

**Describe the bug**
I've recently been integrating Numba's JIT compilation for some of my functions and it seems like Scalene is incompatible with Numba when `parallel=True`  is enabled.

**To Reproduce**
1. Install numba (I used `pip install numba`)
2. Write this minimal example I found from the [numba docs](https://numba.pydata.org/numba-doc/latest/user/parallel.html#numba-parallel). In `testfile.py` I have:
```
import numpy as np
from numba import njit, prange

@njit(parallel=True)
def prange_test(A):
    s = 0
    # Without "parallel=True" in the jit-decorator
    # the prange statement is equivalent to range
    for i in prange(A.shape[0]):
        s += A[i]
    return s

print(prange_test(np.random.rand(6)))
```
3. Run `scalene testfile.py` in command line
4. Program throws an error, gives a very long stack trace:
```
Error in program being profiled:
 Failed in nopython mode pipeline (step: native lowering)
←[1m←[1mcannot find context for 'fork'
←[1m
File "testfile.py", line 42:←[0m
←[1mdef prange_test(A):
    <source elided>
    # the prange statement is equivalent to range
←[1m    for i in prange(A.shape[0]):
←[0m    ←[1m^←[0m←[0m
←[0m
←[0m←[1mDuring: lowering "id=0[LoopNest(index_variable = parfor_index.3, range = (0, $14binary_subscr.5, 1))]{22: <ir.Block at testfile.py (42)>}Var(parfor_index.3, testfile.py:42)" at testfile.py (42)←[0m
Traceback (most recent call last):
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\errors.py", line 823, in new_error_context
    yield
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\lowering.py", line 293, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\lowering.py", line 565, in lower_inst
    func(self, inst)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\parfors\parfor_lowering.py", line 316, in _lower_parfor_parallel
    call_parallel_gufunc(
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\parfors\parfor_lowering.py", line 1462, in call_parallel_gufunc
    _launch_threads()
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\np\ufunc\parallel.py", line 376, in _launch_threads
    _set_init_process_lock()
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\np\ufunc\parallel.py", line 303, in _set_init_process_lock
    ctx = multiprocessing.get_context()
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\replacement_get_context.py", line 12, in replacement_get_context
    return old_get_context("fork")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scalene\scalene_profiler.py", line 1556, in profile_code
    exec(code, the_globals, the_locals)
  File "testfile.py", line 46, in <module>
    print(prange_test(np.random.rand(6)))
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\dispatcher.py", line 487, in _compile_for_args
    raise e
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler.py", line 476, in _compile_core
    raise e
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler_machinery.py", line 353, in run
    raise patched_exception
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\typed_passes.py", line 394, in run_pass
    lower.lower()
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\lowering.py", line 196, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\lowering.py", line 250, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\lowering.py", line 279, in lower_function_body
    self.lower_block(block)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\lowering.py", line 293, in lower_block
    self.lower_inst(inst)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Lance\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numba\core\errors.py", line 837, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
←[1m←[1mcannot find context for 'fork'
←[1m
File "testfile.py", line 42:←[0m
←[1mdef prange_test(A):
    <source elided>
    # the prange statement is equivalent to range
←[1m    for i in prange(A.shape[0]):
←[0m    ←[1m^←[0m←[0m
←[0m
←[0m←[1mDuring: lowering "id=0[LoopNest(index_variable = parfor_index.3, range = (0, $14binary_subscr.5, 1))]{22: <ir.Block at testfile.py (42)>}Var(parfor_index.3, testfile.py:42)" at testfile.py (42)←[0m
```
Note when I instead set `parallel=False` in `testfile.py` , the profile runs without issues. I also ran the program with `parallel=True` on Windows Subsystem for Linux, and it ran with no issues, so I assume it's a Windows compatibility issue.

**Expected behavior**
I expect the program to run without error and a Scalene profile to be generated after completion.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, Version 10.0.19044 Build 19044
 - Python: 3.9.13
 - Numba: 0.55.2
 - Scalene: 1.5.8

**Comment by emeryberger** [comment]
Thanks for the report. Scalene currently only supports the `fork` option for `multiprocessing` (see https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods), which is not available on Windows.

**Comment by replicaacliper** [comment]
I see. Are there plans to add support for the `spawn` option in a future version?

**Comment by emeryberger** [comment]
We will look into it - for now, we'll put in a warning message that it is not yet supported on Windows. Thanks for bringing it to our attention!

**Comment by replicaacliper** [comment]
Thanks for diagnosing the issue so quickly!
