### ISSUE TITLE
Running scalene on remote GPU cluster

### ISSUE THREAD

**Issue by kbkartik** [plasma-umass/scalene#427]
Hi,

I installed scalene and ran for my python file. However, it gives me the following error:

```
Error in program being profiled:
 Function Not Found
Traceback (most recent call last):
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/pynvml/nvml.py", line 782, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1612, in profile_code
    exec(code, the_globals, the_locals)
  File "./code-exp/main.py", line 1, in <module>
    import numpy as np
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.compat._inspect import getargspec
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/numpy/compat/__init__.py", line 12, in <module>
    from . import _pep440
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/numpy/compat/_pep440.py", line 198, in <module>
    _legacy_version_component_re = re.compile(
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/sre_parse.py", line 839, in _parse
    state.closegroup(group, p)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/sre_parse.py", line 97, in closegroup
    self.groupwidths[gid] = p.getwidth()
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/sre_parse.py", line 184, in getwidth
    l, h = av.getwidth()
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/sre_parse.py", line 197, in getwidth
    elif op in _REPEATCODES:
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 719, in cpu_signal_handler
    (gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/scalene/scalene_gpu.py", line 110, in get_stats
    mem_used = self.gpu_memory_usage(self.__pid)
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/scalene/scalene_gpu.py", line 101, in gpu_memory_usage
    for proc in pynvml.nvmlDeviceGetComputeRunningProcesses(handle):
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/pynvml/nvml.py", line 2223, in nvmlDeviceGetComputeRunningProcesses
    return nvmlDeviceGetComputeRunningProcesses_v2(handle);
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/pynvml/nvml.py", line 2191, in nvmlDeviceGetComputeRunningProcesses_v2
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v2")
  File "/home/kube-admin/miniconda3/envs/temporl/lib/python3.8/site-packages/pynvml/nvml.py", line 785, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found
```

Any thoughts on how can I fix this?

**Comment by emeryberger** [comment]
Looks like you need to update pynvml or your NVIDIA driver (or both).

**Comment by kbkartik** [comment]
I am currently using `pvnvml 11.4.1` and nvidia driver `440.59` (CUDA 10.2) for my 1080Ti on Ubuntu 16.04 version. The nvidia driver seems to be the compatible one for my ubuntu version.

**Comment by kbkartik** [comment]
After doing some further testing, it seems that `pynvml` isn't loading the nvml methods. I opened an issue [#311](https://github.com/NVIDIA/k8s-device-plugin/issues/331). Apparently, this is a common issue. Any relevant ideas to fix this would be helpful.

**Comment by emeryberger** [comment]
I believe this has long been resolved.
