### ISSUE TITLE
Invoke using scalene in code 

### ISSUE THREAD

**Issue by sagoyanfisic** [plasma-umass/scalene#431]
**Describe the bug**
I am trying to start the scalene.start() method in the code but I get the following error.

```
import numpy as np

from scalene import scalene_profiler

# Turn profiling on
# scalene_profiler.start()

def main():
    # Turn profiling on
    scalene_profiler.start()
    
    r = list(range(10**7))
    x = np.array(r)
    y = np.random.uniform(0, 100, size=10**8)
    a = np.array(y)
    del r
    del x
    del y
    del a

    # Turn profiling off
    scalene_profiler.stop()

main()
```
output  scalene==1.3.5
```
Traceback (most recent call last):
  File "/Users/xx/Documents/xxx/scripts/main.py", line 24, in <module>
    main()
  File "/Users/xx/Documents/xxx/scripts/main.py", line 10, in main
    scalene_profiler.start()
AttributeError: module 'scalene.scalene_profiler' has no attribute 'start'
```
output  scalene==1.4.2
```
ERROR: Do not try to invoke `start` when you have not called Scalene using one of the methods in https://github.com/plasma-umass/scalene#using-scalene
```

**Desktop (please complete the following information):**
 - OS: Docker Ubuntu 20.00
 - Browser None
 - Version 20.00

**Comment by emeryberger** [comment]
You have to invoke your program using Scalene (as in, `scalene foo.py` or `python3 -m scalene foo.py`).
