### ISSUE TITLE
Scalene stops before creating report

### ISSUE THREAD

**Issue by ArneBachmannDLR** [plasma-umass/scalene#462]
**Describe the bug**
I profile a script like that:
`scalene --html --outfile x.html --memory-leak-detector autocook\__main__.py args`

and get this error after the script finishes successfully:
```
Scalene: An exception of type OSError occurred. Arguments:
(22, 'Invalid argument')
Traceback (most recent call last):
  File "C:\ProgramData\mambaforge\envs\310\lib\site-packages\scalene\scalene_profiler.py", line 1885, in run_profiler
    exit_status = profiler.profile_code(
  File "C:\ProgramData\mambaforge\envs\310\lib\site-packages\scalene\scalene_profiler.py", line 1652, in profile_code
    did_output = Scalene.output_profile()
  File "C:\ProgramData\mambaforge\envs\310\lib\site-packages\scalene\scalene_profiler.py", line 789, in output_profile
    json_output = Scalene.__json.output_profiles(
  File "C:\ProgramData\mambaforge\envs\310\lib\site-packages\scalene\scalene_json.py", line 333, in output_profiles
    with open(full_fname, "r", encoding="utf-8") as source_file:
OSError: [Errno 22] Invalid argument: 'D:\\forks\\HACE\\autocook\\<frozen importlib._bootstrap_external>'
```

It seems that the local file is not correctly found, maybe due to sys.path modifications or import magic (on my part)?

**Expected behavior**
Some kind of success message or clean exit.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Python Version: mambaforge with a Python 3.10 environment

**Comment by emeryberger** [comment]
Please try this with the latest version (1.5.14), which fixes similar issues.

**Comment by emeryberger** [comment]
Closing because I believe this will fix the issue, but please re-open if that's not the case!

**Comment by ArneBachmannDLR** [comment]
My script seems to be invoked fine, but the error message is still showing up afterwards:
```
Scalene: An exception of type OSError occurred. Arguments:
(22, 'Invalid argument')
Traceback (most recent call last):
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_profiler.py", line 1883, in run_profiler
    exit_status = profiler.profile_code(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_profiler.py", line 1650, in profile_code
    did_output = Scalene.output_profile()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_profiler.py", line 788, in output_profile
    json_output = Scalene.__json.output_profiles(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_json.py", line 336, in output_profiles
    with open(full_fname, "r", encoding="utf-8") as source_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'D:\\forks\\HACE\\autocook\\<frozen importlib._bootstrap_external>'
```

It seems to be the string representation of the imported library?
I'm happy to help investigate.

Also #475 .

**Comment by emeryberger** [comment]
Please try to install from the repo version; I added an exception that should handle this case for Windows.
`python3 -m pip install git+https://github.com/plasma-umass/scalene`. Thanks!

**Comment by ArneBachmannDLR** [comment]
Sorry, no dice:

```
scalene --html --outfile x.html --memory-leak-detector autocook\__main__.py --- --help
Autocook V1.14 (C) 2019-2022  Deutsches Zentrum fuer Luft- und Raumfahrt (DLR).  All rights reserved.
... output from my tool...
Scalene: An exception of type OSError occurred. Arguments:
(22, 'Invalid argument')
Traceback (most recent call last):
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_profiler.py", line 1883, in run_profiler
    exit_status = profiler.profile_code(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_profiler.py", line 1650, in profile_code
    did_output = Scalene.output_profile()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_profiler.py", line 788, in output_profile
    json_output = Scalene.__json.output_profiles(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\311\Lib\site-packages\scalene\scalene_json.py", line 336, in output_profiles
    with open(full_fname, "r", encoding="utf-8") as source_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'D:\\forks\\HACE\\autocook\\<frozen importlib._bootstrap_external>'
```

**Comment by emeryberger** [comment]
Something seems amiss; while I couldn't run your code, I verified that the OSError exception should catch this -- perhaps try to uninstall Scalene first and then re-install from the repo.

Another note: memory profiling is not _yet_ enabled on Windows, sorry!

**Comment by ArneBachmannDLR** [comment]
Not sure what happened, but after pip uninstall and reinstall from Git it suddenly worked (under Python 3.11)!

**Comment by walker2041** [comment]
I started out having the exact same issue as above, but now I'm having trouble with installing from the repo. Running on windows 10 with a python 3.10.8 venv
Getting the following error:
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
          from wheel.bdist_wheel import bdist_wheel
      ModuleNotFoundError: No module named 'wheel'

![image](https://user-images.githubusercontent.com/91851972/200916797-12118e12-c6c1-4a66-8af1-e7d8fb189954.png)

**Comment by ArneBachmannDLR** [comment]
I'm not proficient with virtualenv (only conda envs, I'm on Windows), did you try to `pip install wheel` to avoid the problem?

**Comment by Wissotsky** [comment]
Can confirm uninstalling scalene and reinstalling from git works.
If you encounter wheel issues just `pip install wheel` seems to fix it.
Works fine with venv
