### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by mkst** [plasma-umass/scalene#467]
**Describe the bug**

The following exception is thrown, unsure the impact as this is my first time using scalene
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scalene/scalene_sigqueue.py", line 48, in run
    self.process(*item)
  File "/usr/local/lib/python3.10/dist-packages/scalene/scalene_profiler.py", line 1273, in alloc_sigqueue_processor
    last_file, last_line = Scalene.__invalidate_queue.pop(0)
IndexError: pop from empty list
```

**To Reproduce**

I'm trying to profile [splat](https://github.com/ethteck/splat), as part of [sssv](https://github.com/mkst/sssv) decomp...reproduction steps will be difficult, but i'm just running:

```sh
scalene tools/splat/split.py sssv.us.yaml
```

**Expected behavior**
No exceptions thrown for usual behaviour.

**Desktop (please complete the following information):**
 - OS: Ubuntun22.04
 - Browser: n/a
 - Version `Scalene version 1.5.13`

**Additional context**
I can't get scalene to serve anything up, unsure if thats related to this exception or just my bad luck..

**Comment by Force1ess** [comment]
Same problem, this problem happened when I tried to use scalene with multiprocessing or concurrent process pool

**Comment by emeryberger** [comment]
If you can provide a minimal working example (ok, "non-working") that would be immensely helpful - thanks!
