### ISSUE TITLE
nvml.NVMLError_NotSupported on GTX 560 Ti

### ISSUE THREAD

**Issue by u8sand** [plasma-umass/scalene#469]
**Describe the bug**

scalene >= 1.5.9 & the latest github release causes a GPU Not Supported error on my system. It works prior to this release.

In any case, I don't need GPU profiling, is there no way to disable it? (--cpu-only doesn't seem to do this despite its name)

**To Reproduce**
1.  
```
pip install scalene
echo "import time; time.sleep(1)" > myscript.py
scalene myscript.py
```
2. See error

**Expected behavior**
I'd expect it to work, disabling the GPU feature which is not supported on my GPU.

**Screenshots**

The traceback is below:
```
Error in program being profiled:
 Not Supported
Traceback (most recent call last):
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 1633, in profile_code
    exec(code, the_globals, the_locals)
  File "myscript.py", line 1, in <module>
    import time; time.sleep(1)
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 733, in cpu_signal_handler
    (gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_gpu.py", line 109, in get_stats
    total_load = self.gpu_utilization(self.__pid)
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_gpu.py", line 77, in gpu_utilization
    utilization += pynvml.nvmlDeviceGetUtilizationRates(h).gpu
  File "/home/u8sand/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 2137, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "/home/u8sand/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
Scalene: Program did not run for long enough to profile.
```

**Desktop (please complete the following information):**
```
OS:
  Kernel: Linux 6.0.2-arch1-1
  Distribution: Arch Linux
GPU:
  UMD Version: NVIDIA 390.154
  Model: GF114 [GeForce GTX 560 Ti]
  OpenGL Version: 4.60 NVIDIA
```

**Additional context**
It seems related to #262 but as it affects the latest release it is either different or has been re-introduced.

The GPU on this system is old, but I don't need GPU profiling. Thanks for the well made python profiler!

**Comment by emeryberger** [comment]
Thanks for the report. Can you change the file `scalene_gpu.py` in your `site-packages` directory as follows?

Change line 109 from:
```            total_load = self.gpu_utilization(self.__pid)```

to:
```            total_load = 0.0```

If that also fails, please change the following line to `mem_used = 0.0`. I will patch the code to handle these cases gracefully, depending on the outcome. Thanks!

**Comment by u8sand** [comment]
Thank you for the speedy response. I've made the changes you suggested with the following effects:

>Change line 109 from: `total_load = self.gpu_utilization(self.__pid)`
```python
Error in program being profiled:
 Function Not Found
Traceback (most recent call last):
  File "/home/u8sand/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 782, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 1633, in profile_code
    exec(code, the_globals, the_locals)
  File "myscript.py", line 1, in <module>
    import time; time.sleep(1)
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 733, in cpu_signal_handler
    (gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_gpu.py", line 110, in get_stats
    mem_used = self.gpu_memory_usage(self.__pid)
  File "/home/u8sand/.local/lib/python3.10/site-packages/scalene/scalene_gpu.py", line 101, in gpu_memory_usage
    for proc in pynvml.nvmlDeviceGetComputeRunningProcesses(handle):
  File "/home/u8sand/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 2223, in nvmlDeviceGetComputeRunningProcesses
    return nvmlDeviceGetComputeRunningProcesses_v2(handle);
  File "/home/u8sand/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 2191, in nvmlDeviceGetComputeRunningProcesses_v2
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v2")
  File "/home/u8sand/.local/lib/python3.10/site-packages/pynvml/nvml.py", line 785, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found
Scalene: Program did not run for long enough to profile.
```

>If that also fails, please change the following line to mem_used = 0.0.

After this it seems to be working.

**Comment by emeryberger** [comment]
Please try to install Scalene from the git repo as follows and let me know if it works now.

`python3 -m pip install git+https://github.com/plasma-umass/scalene`

Thanks!

**Comment by u8sand** [comment]
@emeryberger Looks like it's working, thanks again!
