### ISSUE TITLE
pynvml.nvml.NVMLError_Unknown: Unknown Error when profiling CPU only

### ISSUE THREAD

**Issue by BeatWolf** [plasma-umass/scalene#471]
When profiling my application which does not use any GPU i get the following error:

```
Error in program being profiled:
 Unknown Error                                                                                                                     
Traceback (most recent call last):                                                                                                 
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\scalene\scalene_profiler.py", line 1633, in profile_code
    exec(code, the_globals, the_locals)                                                                                            
  File "tp-code-similarity.py", line 3, in <module>                                                                                
    from sklearn.decomposition import PCA                                                                                          
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\sklearn\__init__.py", line 82, in <module>              
    from .base import clone                                                                                                        
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\sklearn\utils\__init__.py", line 26, in <module>
    from . import _joblib
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\sklearn\utils\_joblib.py", line 7, in <module>
    import joblib
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\joblib\__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\joblib\parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\joblib\_parallel_backends.py", line 13, in <module>
    from .my_exceptions import WorkerInterrupt
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\joblib\my_exceptions.py", line 3, in <module>
    from . import _deprecated_my_exceptions
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\scalene\scalene_profiler.py", line 733, in cpu_signal_handler
    (gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\scalene\scalene_gpu.py", line 109, in get_stats
    total_load = self.gpu_utilization(self.__pid)
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\scalene\scalene_gpu.py", line 77, in gpu_utilization
    utilization += pynvml.nvmlDeviceGetUtilizationRates(h).gpu
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\pynvml\nvml.py", line 2137, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "C:\Users\beat.wolf\PycharmProjects\tp-tools\venv\lib\site-packages\pynvml\nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Unknown: Unknown Error
```

I tried to disable GPU related profiling with --cpu-only, but i get the same error.

I finaly found a workaround by modifying line 733 in scalene_profiler.py from:
`(gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()`

to

`(gpu_load, gpu_mem_used) = (0,0)`

This works but should probably be the default behaviour when profiling CPU only

**Comment by emeryberger** [comment]
Please try to install Scalene from the git repo as follows and let me know if it works now.

`python3 -m pip install git+https://github.com/plasma-umass/scalene`

Thanks!

**Comment by emeryberger** [comment]
Also, can you let me know what kind of GPU your system has? (And yes, `--cpu-only` is currently a misnomer; there's an open issue to fix this.) Thanks!

**Comment by laurapons** [comment]
I am having the same issue. I'm working with PyCharm, I created a virtual environment and running everything in the virtual environment. I got the following:

```
File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_profiler.py", line 851, in cpu_signal_handler
    (gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_gpu.py", line 126, in get_stats
    total_load = self.gpu_utilization(self.__pid)
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_gpu.py", line 87, in gpu_utilization
    utilization += pynvml.nvmlDeviceGetUtilizationRates(h).gpu
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\pynvml\nvml.py", line 2137, in nvmlDeviceGetUtilizationRates
    _nvmlCheckReturn(ret)
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\pynvml\nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Unknown: Unknown Error
Scalene: Program did not run for long enough to profile.
NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization.
Run once as Administrator or root (i.e., prefixed with `sudo`) to enable per-process GPU accounting.

```
Python3.8

![image](https://user-images.githubusercontent.com/1275184/212125490-88e73d8f-cede-4237-af56-9d77cd060767.png)

**Comment by emeryberger** [comment]
Hi @laurapons - please try again with the repo version. The patch allows Scalene to work but in the face of this kind of error, there's no way for it to provide GPU profiling.

**Comment by laurapons** [comment]
Thanks for checking it. It does not break, but it does not provide the memory profiling either. Do you think it could be caused by using a virtualenv?

**Comment by emeryberger** [comment]
Scalene does not yet perform memory profiling on Windows platforms.

**Comment by Mike-ihr** [comment]
> Please try to install Scalene from the git repo as follows and let me know if it works now.
> 
> `python3 -m pip install git+https://github.com/plasma-umass/scalene`
> 
> Thanks!

it have tried, but it doesn't work
