### ISSUE TITLE
Scalene crash when using Qt / PySide

### ISSUE THREAD

**Issue by tomas16** [plasma-umass/scalene#473]
**Describe the bug**
Scalene crashes when the code imports from PySide.

Source code (qtexample.py):
```python
from PySide6.QtCore import QObject
```

Traceback:
```
tomas$ scalene qtexample.py
Scalene: An exception of type FileNotFoundError occurred. Arguments:
(2, 'No such file or directory')
Traceback (most recent call last):
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1888, in run_profiler
    exit_status = profiler.profile_code(
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1654, in profile_code
    did_output = Scalene.output_profile()
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 792, in output_profile
    json_output = Scalene.__json.output_profiles(
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_json.py", line 331, in output_profiles
    with open(full_fname, "r", encoding="utf-8") as source_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tomas/MyProject/shibokensupport/signature/loader.py'
```

The error changes slightly when subclassing QObject. Source code (qtexample.py):
```python
from PySide6.QtCore import QObject

class MyClass(QObject):
    pass
```

Traceback:
```
tomas$ scalene qtexample.py
Scalene: An exception of type FileNotFoundError occurred. Arguments:
(2, 'No such file or directory')
Traceback (most recent call last):
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1888, in run_profiler
    exit_status = profiler.profile_code(
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1654, in profile_code
    did_output = Scalene.output_profile()
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 792, in output_profile
    json_output = Scalene.__json.output_profiles(
  File "/Users/tomas/opt/miniconda3/envs/myenv/lib/python3.8/site-packages/scalene/scalene_json.py", line 331, in output_profiles
    with open(full_fname, "r", encoding="utf-8") as source_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tomas/MyProject/shibokensupport/signature/loader.py'
```

It looks like the shiboken library used by PySide confuses scalene about the source code filename (which should be '/Users/tomas/MyProject/qtexample.py' in this case).

**Desktop (please complete the following information):**
- OS: macOS 12.6 (21G115)
- python 3.8.13
- scalene 1.5.13
- pyside6 6.3.1
- shiboken6 6.3.1

**Comment by emeryberger** [comment]
Just to verify, can you please try with the latest version (1.5.14)?

**Comment by tomas16** [comment]
Yes, those examples work now, thanks! I created a new env because the latest version wasn't available from conda yet, so there are a few other version changes:

- python 3.8.13
- scalene 1.5.14
- pyside6 6.4.0
- shiboken6 6.4.0

Unfortunately the Qt-based application I'm trying to profile hangs when I run it with scalene. I'll see if I can figure out what's going on.

Thanks again for the quick response!
