### ISSUE TITLE
AttributeError: module 'ast' has no attribute 'unparse' - Not supported for python 3.8

### ISSUE THREAD

**Issue by laurapons** [plasma-umass/scalene#544]
**Describe the bug**
scalene example.py fails
I run it with python 3.8, and according to the documentation unparse was added on 3.9. Is there any way to bypass the error?

`Scalene failed to initialize.
Traceback (most recent call last):
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_profiler.py", line 2000, in run_profiler
    exit_status = profiler.profile_code(
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_profiler.py", line 1810, in profile_code
    did_output = Scalene.output_profile()
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_profiler.py", line 909, in output_profile
    json_output = Scalene.__json.output_profiles(
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_json.py", line 381, in output_profiles
    imports = ScaleneAnalysis.get_native_imported_modules(code_str)
  File "D:\Dev\ExplorationProject\venv\lib\site-packages\scalene\scalene_analysis.py", line 78, in get_native_imported_modules
    imported_modules.append(ast.unparse(node))
AttributeError: module 'ast' has no attribute 'unparse'
`

**Desktop (please complete the following information):**
 - OS: Windows 11
- PyCharm 2022.2.4
- Python3.8

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.
I already tried it with the command above.

**Additional context**
I created a virtual environment that I use.

**Comment by laurapons** [comment]
Using astunparse would fix the issue for python 3.8

**Comment by emeryberger** [comment]
Thanks for your report! I believe this fixes the issue. Please let me know!

**Comment by laurapons** [comment]
Yes, thanks! It worked, but I still have the same issue here https://github.com/plasma-umass/scalene/issues/471 (it was closed, but I believe it was not fixed, would be worse to reopen it and take a look, I provided all the information in there).
