### ISSUE TITLE
Cannot run scalene on windows11

### ISSUE THREAD

**Issue by link-er** [plasma-umass/scalene#550]
Hello

I am trying to profile the memory usage of my python script that I am running on Windows11 (64bit) and GPU with NVIDIA.
The pip installs the package smoothly, but when I run ```scalene script.py``` I get a window with error saying that the program "...\scalene\python.exe" cannot start due to incompatibility with 64-bit versions of Windows.
I am using conda environment and running the script from Anaconda prompt.

Is there any way to use scalene in such case?

**Comment by emeryberger** [comment]
Have you tried the version in the repository? Please provide some more details - thanks.

**Comment by link-er** [comment]
Hi,

I am installing via pip install, getting version 1.5.19.
When I run the script I get first a window with error, when I close it the following stack is printed:
```
scalene run_training_CIFAR10_FAM.py
Global seed set to 1411774898
Error in program being profiled:
 [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
Traceback (most recent call last):
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\scalene\scalene_profiler.py", line 1785, in profile_code
    exec(code, the_globals, the_locals)
  File "run_training_CIFAR10_FAM.py", line 17, in <module>
    wandb.login(key='78c3a5d7528fa54899145d20403f9ee3a0420acd') #lina: 'bd3cef02a137bf971cabfd5f420b3f96c7f8b801')
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_login.py", line 74, in login
    if wandb.setup()._settings._noop:
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_setup.py", line 307, in setup
    ret = _setup(settings=settings)
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_setup.py", line 302, in _setup
    wl = _WandbSetup(settings=settings)
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_setup.py", line 288, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_setup.py", line 106, in __init__
    self._setup()
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_setup.py", line 262, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\wandb_manager.py", line 112, in __init__
    self._service.start()
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\service\service.py", line 137, in start
    self._launch_server()
  File "C:\Users\adylo\anaconda3\envs\fam\lib\site-packages\wandb\sdk\service\service.py", line 124, in _launch_server
    internal_proc = subprocess.Popen(
  File "C:\Users\adylo\anaconda3\envs\fam\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\adylo\anaconda3\envs\fam\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization.
Run once as Administrator or root (i.e., prefixed with `sudo`) to enable per-process GPU accounting.
```
Then the browser opens the page with first import lines of the script.

**Comment by space-nuko** [comment]
Same error, Windows Server 2022

```
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 8e439067bc6d197b4b672438a0ca6114d3cc7a6c
Error in program being profiled:
 Error running command.
Command: "C:\Users\a\AppData\Local\Temp\scalene1azjym5b\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: This version of C:\Users\a\AppData\Local\Temp\scalene1azjym5b\python.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.


Traceback (most recent call last):
  File "E:\sd\venv\lib\site-packages\scalene\scalene_profiler.py", line 1835, in profile_code
    exec(code, the_globals, the_locals)
  File "launch.py", line 380, in <module>
    prepare_environment()
  File "launch.py", line 287, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "launch.py", line 137, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\Users\a\AppData\Local\Temp\scalene1azjym5b\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: This version of C:\Users\a\AppData\Local\Temp\scalene1azjym5b\python.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.


Scalene: Program did not run for long enough to profile.
NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization.
Run once as Administrator or root (i.e., prefixed with `sudo`) to enable per-process GPU accounting.
```
