### ISSUE TITLE
Scalene fails to profile code importing flask

### ISSUE THREAD

**Issue by robin-vagner** [plasma-umass/scalene#575]
**Bug description**
I am trying to profile a tool that uses flask, and scalene throws different exceptions each time I run the program, such as :
```
Error in program being profiled:
 No module named 'werkzeug.sansio.multipart'
Traceback (most recent call last):
  File "C:\Users\robin.vagner\unit-image\source\scalene_test_venv\lib\site-packages\scalene\scalene_profiler.py", line 1835, in profile_code
    exec(code, the_globals, the_locals)
  File "C:\Users\robin.vagner\Desktop\failing_script.py", line 1, in <module>
    import flask
  File "C:\Users\robin.vagner\unit-image\source\scalene_test_venv\lib\site-packages\flask\__init__.py", line 4, in <module>
    from . import json as json
  File "C:\Users\robin.vagner\unit-image\source\scalene_test_venv\lib\site-packages\flask\json\__init__.py", line 8, in <module>
    from ..globals import current_app
  File "C:\Users\robin.vagner\unit-image\source\scalene_test_venv\lib\site-packages\flask\globals.py", line 4, in <module>
    from werkzeug.local import LocalProxy
  File "C:\Users\robin.vagner\unit-image\source\scalene_test_venv\lib\site-packages\werkzeug\__init__.py", line 2, in <module>
    from .test import Client as Client
  File "C:\Users\robin.vagner\unit-image\source\scalene_test_venv\lib\site-packages\werkzeug\test.py", line 29, in <module>
    from .sansio.multipart import Data
ModuleNotFoundError: No module named 'werkzeug.sansio.multipart'
```

Other exceptions being thrown are `No module named 'email.feedparser'`, `[WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap_external>'`, `[WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'`.

All those errors originate from the same line as the one in the given traceback in `profile_code`.

**To Reproduce**
1. Create the following python script :
```python
import flask
print(flask)
```
2. Install scalene and flask in a virtual environment (I tested it with python 3.9.13)
3. Run `python -m scalene <path\to\my\script.py>`

**Expected behavior**
No exception thrown (I do not expect scalene to do profiling with this test script since it does not run long enough).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.9.13
 - Scalene Version: 1.5.20 (same result with the repository version)

**Comment by amirebrahimi** [comment]
Also seeing this same error with `numpy` with a simple test file:
```python
import numpy as np

cumulative = np.zeros(32)
for i in range(10000):
    cumulative += np.random.random(32)
print(cumulative)
```
