### ISSUE TITLE
Unable to profile muptiprocessing Queue

### ISSUE THREAD

**Issue by stopmosk** [plasma-umass/scalene#579]
**Describe the bug**
Error when trying to use python multiprocessing Queue:
```
Can't pickle local object 'replacement_mp_semlock.<locals>.ReplacementSemLock'
```

**To Reproduce**
1. Run the simple script `mpq.py`:
```python
import multiprocessing as mp


def queue_put(queue, text):
    print(f'Put text "{text}" on queue: {queue}')
    queue.put(text)


if __name__ == "__main__":
    q = mp.Queue()
    p = mp.Process(target=queue_put, args=(q, 'test'))

    p.start()
    p.join()
```
2. See error:
```
Error in program being profiled:
 Can't pickle local object 'replacement_mp_semlock.<locals>.ReplacementSemLock'
Traceback (most recent call last):
  File "C:\python\lib\site-packages\scalene\scalene_profiler.py", line 1835, in profile_code
    exec(code, the_globals, the_locals)
  File ".\mpq.py", line 13, in <module>
    p.start()
  File "C:\python\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\python\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\python\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\python\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'replacement_mp_semlock.<locals>.ReplacementSemLock'
Scalene: Program did not run for long enough to profile.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python\Lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect
```

**Expected behavior**
Expected output:
```
Put text "test" on queue: <multiprocessing.queues.Queue object at 0x0000028FCE711450>
```

**Desktop (please complete the following information):**
 - OS: Windows 11, PowerShell

**Additional context**
Example without using Queue works fine:
```python
import multiprocessing as mp


def print_func(arg):
    print(arg, end=' ')


if __name__ == "__main__":
    processes = []
    for arg in range(50):
        p = mp.Process(target=print_func, args=(arg,))
        processes.append(p)
        p.start()

    for p in processes:
        p.join()
```

*Output:*
```
0 2 5 1 4 12 10 6 11 3 13 8 19 9 15 17 7 14 21 30 42 23 22 34 43 20 26 40 44 35 27 24 39 29 47 36 48 25 28 31 16 46 18 33 38 45 41 32 37 49
                                    .\mp.py: % of time =  44.05% (630.777ms) out of 1.432s.                         
+-----------------------------------------------------------------------------------------------------------------------------+
|       |Time    |–––––– |–––––– |                                                                                            |
| Line  |Python  |native |system |.\mp.py                                                                                     |
|-------+--------+-------+-------+--------------------------------------------------------------------------------------------|
|     1 |        |       |       |import multiprocessing as mp                                                                |
|     2 |        |       |       |                                                                                            |
|     3 |        |       |       |                                                                                            |
|     4 |        |       |       |def print_func(arg):                                                                        |
|     5 |        |       |       |    print(arg, end=' ')                                                                     |
|     6 |        |       |       |                                                                                            |
|     7 |        |       |       |                                                                                            |
|     8 |        |       |       |if __name__ == "__main__":                                                                  |
|     9 |        |       |       |    processes = []                                                                          |
|    10 |        |       |       |    for arg in range(50):                                                                   |
|    11 |        |       |       |        p = mp.Process(target=print_func, args=(arg,))                                      |
|    12 |        |       |       |        processes.append(p)                                                                 |
|    13 |    2%  |       |  41%  |        p.start()                                                                           |
|    14 |        |       |       |                                                                                            |
|    15 |        |       |       |    for p in processes:                                                                     |
|    16 |        |       |       |        p.join()                                                                            |
|    17 |        |       |       |                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------+
```

**Comment by emeryberger** [comment]
Should be fixed by https://github.com/plasma-umass/scalene/commit/5e6982e49d0bacc084ec324fa9649b1192cc3593. Please update and try again!
