### ISSUE TITLE
Can't run `scalene.profile` on Windows

### ISSUE THREAD

**Issue by space-nuko** [plasma-umass/scalene#583]
**Describe the bug**
On Windows Server 2022 I get this error with `scalene.profile`

```bash
$ python -m scalene.profile --pid 38216 --on
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\sd\venv\lib\site-packages\scalene\profile.py", line 34, in <module>
    os.kill(args.pid, ScaleneSignals().start_profiling_signal)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Desktop (please complete the following information):**
 - OS: Windows Server 2022 20348.1249
 - Browser: Chrome
 - Version: 1.5.20

**Comment by emeryberger** [comment]
Unfortunately, Scalene does not currently support this kind of profiling on Windows. We need to change the usage instructions for that platform. Sorry for the inconvenience.
