### ISSUE TITLE
Profiling fails when GPU present but not in use

### ISSUE THREAD

**Issue by rossbar** [plasma-umass/scalene#591]
**Describe the bug**

I get an `pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found` exception on a multi-gpu system when attempting to profile code that does not make use of a GPU.

**To Reproduce**

I've only observed this on systems with multiple GPUs where I do not necessarily have root access to the machine. Perhaps a multi-gpu cloud instance would be sufficient to reproduce:

```bash
$ python -m venv prof
$ source prof/bin/activate
$ pip list  # Verify environment is "clean"
$ pip install scalene numpy
$ echo "import numpy as np" >> foo.py  # Create minimal script to profile
$ scalene --cpu --memory foo.py
```

which results in

<details>
  <summary>Traceback from above example</summary>
<pre>
Error in program being profiled:
 Function Not Found
Traceback (most recent call last):
  File "/home/rossbar/prof/lib/python3.10/site-packages/pynvml/nvml.py", line 850, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rossbar/prof/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 1835, in profile_code
    exec(code, the_globals, the_locals)
  File "foo.py", line 1, in <module>
    import numpy as np
  File "/home/rossbar/prof/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/home/rossbar/prof/lib/python3.10/site-packages/numpy/core/__init__.py", line 101, in <module>
    from . import _add_newdocs
  File "/home/rossbar/prof/lib/python3.10/site-packages/numpy/core/_add_newdocs.py", line 6947, in <module>
    refer_to_array_attribute('setflags'))
  File "/home/rossbar/prof/lib/python3.10/site-packages/numpy/core/_add_newdocs.py", line 6760, in refer_to_array_attribute
    return attr, docstring.format("method" if method else "attribute", attr)
  File "/home/rossbar/prof/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 858, in cpu_signal_handler
    (gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()
  File "/home/rossbar/prof/lib/python3.10/site-packages/scalene/scalene_gpu.py", line 131, in get_stats
    mem_used = self.gpu_memory_usage(self.__pid)
  File "/home/rossbar/prof/lib/python3.10/site-packages/scalene/scalene_gpu.py", line 119, in gpu_memory_usage
    for proc in pynvml.nvmlDeviceGetComputeRunningProcesses(handle):
  File "/home/rossbar/prof/lib/python3.10/site-packages/pynvml/nvml.py", line 2608, in nvmlDeviceGetComputeRunningProcesses
    return nvmlDeviceGetComputeRunningProcesses_v3(handle);
  File "/home/rossbar/prof/lib/python3.10/site-packages/pynvml/nvml.py", line 2576, in nvmlDeviceGetComputeRunningProcesses_v3
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v3")
  File "/home/rossbar/prof/lib/python3.10/site-packages/pynvml/nvml.py", line 853, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found
Scalene: Program did not run for long enough to profile.
NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization.
Run once as Administrator or root (i.e., prefixed with `sudo`) to enable per-process GPU accounting.
</pre>
</details>

**Expected behavior**
As noted this very likely stems from system-specific configuration of a multi-user system with multiple gpus. However, it'd be great if there were a way to avoid attempting to introspect the GPUs altogether so that it is possible to profile cpu/memory-only code on such systems. Perhaps it's possible to skip the `Scalene.__gpu.get_stats()` call when the `--gpu` flag isn't toggled, or add a `--no-gpu` flag to explicitly signal that all GPU introspection should be avoided.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, 5.15.0-67-generic
 - Browser: N/A
 - Version: Scalene version 1.5.20 (2023.02.27)

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.

**Additional context**
One (potentially) interesting note is that the exception is only raised when numpy is imported. If instead you replace the `import numpy as np` line with pure Python (e.g. `print("Hello world")`) then the exception is not triggered.

These multi-user systems typically rely on containerization to manage resources, so the workaround will be to run in a container.

**Comment by rossbar** [comment]
A quick follow-up: I still see this error inside the container. I tried a few different versions of `scalene` and noticed that I started seeing it as of version `1.5.9`. I have downgraded to 1.5.8 for the time being.

**Comment by wence-** [comment]
This is a bug in pynvml (being tracked and should be fixed in an upcoming release): new versions of pynvml are not compatible with old cuda toolkit installs. If you downgrade pynvml `pip install pynvml<11.5` in your environment, things should work.

**Comment by emeryberger** [comment]
Just pushed a new version of Scalene (1.5.21) that enforces this requirement. @wence- can you please post an update when this is fixed? Thanks!
