### ISSUE TITLE
winError 123 when running a program that uses numpy

### ISSUE THREAD

**Issue by adnaneGdihi** [plasma-umass/scalene#623]
**Describe the bug**
error in importing numpy files for illegal characters or other reasons. the error is not clear and does not give much details.

**To Reproduce**
1. install numpy
2. run a program using scalene
3. See error

**Expected behavior**
running the profiling as expected with no import issues

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Python 3.8.10
 - scalene 1.5.21.3

```
Error in program being profiled:
 [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\scalene\scalene_profiler.py", line 1835, in profile_code
    exec(code, the_globals, the_locals)
  File "CNNSegmentationMain.py", line 5, in <module>
    import numpy as np
  File "c:\program files\python38\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "c:\program files\python38\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "c:\program files\python38\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "c:\program files\python38\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
  File "c:\program files\python38\lib\site-packages\scalene\scalene_profiler.py", line 863, in cpu_signal_handler
    Scalene.compute_frames_to_record(),
  File "c:\program files\python38\lib\site-packages\scalene\scalene_profiler.py", line 1236, in compute_frames_to_record
    while not Scalene.should_trace(fname):
  File "c:\program files\python38\lib\site-packages\scalene\scalene_profiler.py", line 1606, in should_trace
    resolved_filename = str(pathlib.Path(filename).resolve()).lower()
  File "c:\program files\python38\lib\pathlib.py", line 1181, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "c:\program files\python38\lib\pathlib.py", line 206, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
Scalene: Program did not run for long enough to profile.
NOTE: The GPU is currently running in a mode that can reduce Scalene's accuracy when reporting GPU utilization.
Run once as Administrator or root (i.e., prefixed with `sudo`) to enable per-process GPU accounting.
```

**Comment by emeryberger** [comment]
Please try the repo version (`python -m pip install -U git+https://github.com/plasma-umass/scalene`).

**Comment by adnaneGdihi** [comment]
downloading the new version from the repo was able to fix the issue. However, I still don't understand the problem's origin.

**Comment by emeryberger** [comment]
For some reason, it was looking for a file that didn’t exist (which it theoretically shouldn’t do). That case is now detected and handled. Thanks for the report and for checking the latest version!
