### ISSUE TITLE
Scalene with Mashumaro causes InvalidFieldValue when profiling dbt application

### ISSUE THREAD

**Issue by PedramNavid** [plasma-umass/scalene#627]
**Describe the bug**
When attempting to run scalene on the `dbt-core` application, I receive a `InvalidFieldValue('_lock',scalene.replacement_mp_lock.replacement_mp_semlock.<locals>.ReplacementSemLock,d['_lock'],cls)` error.

**To Reproduce**
1. Start with an empty python venv `python -m venv .venv`
2. Activate the venv `source ./.venv/bin/activate`
3. Install the dbt-core package `pip install dbt-core==1.4.6 scalene`
4. Change to the dbt folder: `cd .venv/lib/python3.10/site-packages/dbt`
5. Confirm running the CLI works `python cli/main.py`
6. Attempt to use scalene `scalene cli/main.py`
7. Get InvalidFieldValue exception

Please include a minimum working example if at all possible.

**Full Traceback**
```
.venv ❯ scalene cli/main.py
Error in program being profiled:
 invalid syntax (<string>, line 157)
Traceback (most recent call last):
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 1836, in profile_code
    exec(code, the_globals, the_locals)
  File "cli/main.py", line 6, in <module>
    from dbt.adapters.factory import adapter_management
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/dbt/adapters/factory.py", line 8, in <module>
    from dbt.adapters.base.plugin import AdapterPlugin
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/dbt/adapters/base/__init__.py", line 6,in <module>
    from dbt.adapters.base.connections import BaseConnectionManager  # noqa
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/dbt/adapters/base/connections.py", line35, in <module>
    from dbt.contracts.graph.manifest import Manifest
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/dbt/contracts/graph/manifest.py", line 590, in <module>
    class Manifest(MacroMethods, DataClassMessagePackMixin, dbtClassMixin):
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/mashumaro/mixins/dict.py", line 24, in __init_subclass__
    compile_mixin_unpacker(cls, **builder_params["unpacker"])
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/mashumaro/core/meta/mixin.py", line 49,in compile_mixin_unpacker
    builder.add_unpack_method()
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/mashumaro/core/meta/code/builder.py", line 394, in add_unpack_method
    self.compile()
  File "/Users/pedram/repos/scalene-fail/.venv/lib/python3.10/site-packages/mashumaro/core/meta/code/builder.py", line 240, in compile
    exec(code, self.globals, self.__dict__)
  File "<string>", line 157
    raise InvalidFieldValue('_lock',scalene.replacement_mp_lock.replacement_mp_semlock.<locals>.ReplacementSemLock,d['_lock'],cls)
                                                                                       ^
SyntaxError: invalid syntax
Scalene: Program did not run for long enough to profile.

```

**Desktop (please complete the following information):**
 - OS: Mac OS (Apple Silicon)

**Additional context**
- Have tried both the release and git version of scalene.
- Mashumaro uses `exec` on line 240 in `mashumaro/core/meta/code/builder.py` possibly causing this?

**Comment by emeryberger** [comment]
Reproduced locally on Mac.

**Comment by sternj** [comment]
The issue is that, deep inside of mashumaro, a name being written to a Python file as a string was derived with the f-string `"{typ.__module__}.{typ.__qualname__}" `. Because of some details of how Scalene works, we override a Lock type with one that we create, and the class that we replace it with is created inside a function. By default, the `__qualname__` field of that type is `[function_name].<locals>.[class_name]`. Simply overriding this variable with `[function_name].[class_name]` did the trick!

**Comment by PedramNavid** [comment]
thank you! looks like that was a fun one to hunt down
