### ISSUE TITLE
ast.parse crashes in certain edge cases

### ISSUE THREAD

**Issue by D-VR** [plasma-umass/scalene#843]
**Describe the bug**
It seems like in certain cases scalene will feed parts of comments into ast.parse, which then causes a crash.
This is more likely to happen if you increase the profiling frequency.

see two example crashes:

```
Scalene: An exception of type SyntaxError occurred. Arguments:
('unterminated triple-quoted string literal (detected at line 51)', ('<unknown>', 33, 9, '        """%s', 33, 9))
Traceback (most recent call last):
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_profiler.py", line 2120, in run_profiler
    exit_status = profiler.profile_code(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_profiler.py", line 1783, in profile_code
    did_output = Scalene.output_profile(left)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_profiler.py", line 838, in output_profile
    json_output = Scalene.__json.output_profiles(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_json.py", line 486, in output_profiles
    enclosing_regions = ScaleneAnalysis.find_regions(code_str)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_analysis.py", line 109, in find_regions
    tree = ast.parse(src)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 33
    """%s
    ^
SyntaxError: unterminated triple-quoted string literal (detected at line 51)
```

```
('unterminated string literal (detected at line 593)', ('<unknown>', 593, 17, "      Each group's index will be passed to the user defined function", 593, 17))
Traceback (most recent call last):
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_profiler.py", line 2120, in run_profiler
    exit_status = profiler.profile_code(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_profiler.py", line 1783, in profile_code
    did_output = Scalene.output_profile(left)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_profiler.py", line 838, in output_profile
    json_output = Scalene.__json.output_profiles(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_json.py", line 486, in output_profiles
    enclosing_regions = ScaleneAnalysis.find_regions(code_str)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "user/venv/lib/python3.12/site-packages/scalene/scalene_analysis.py", line 109, in find_regions
    tree = ast.parse(src)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 593
    Each group's index will be passed to the user defined function
              ^
SyntaxError: unterminated string literal (detected at line 593)

```

**To Reproduce**

```bash
git clone https://github.com/fkie-cad/ipal_ids_framework.git
cd ipal_ids_framework
python3 -m venv venv
source venv/bin/activate
pip install .
pip install scalene

source venv/bin/activate

echo "from ipal_iids import iids\n\
from scalene import scalene_profiler\n\
if __name__ == \"__main__\":\n\
    scalene_profiler.start()\n\
    iids.main()\n\
    scalene_profiler.stop()\n\
" > test.py

scalene --profile-all --profile-exclude threading.py,dataclasses.py --stacks --cli --cpu --memory --json --outfile test.json --cpu-sampling-rate 0.0001 test.py --- -h

```
**Expected behavior**
Scalene should run through and generate a profile json

**Desktop (please complete the following information):**
- Ubuntu 24.04
- i'm on the most recent commit ( python3 -m pip install git+https://github.com/plasma-umass/scalene)

**Additional context**
-

**Comment by D-VR** [comment]
the easiest way to handle this could be to  wrap the call in scalene_analysis  in a try / except block.

another possibility could be to escape single ' , " or """, although that may cause more headaches. (filtering out comment blocks in a previous step might be better, but I havent looked at the scalene source code)

Ofc this only holds if this is actually the underlying issue.

**Comment by D-VR** [comment]
I have found the issue I think.

If you remove the "strip_magic_line" function, scalene no longer crashes!
The description says:
>  # Filter out any magic lines (starting with %) if in a Jupyter notebook

Yet there is no actual check if the function is called in a jupyter notebook.

```python
    @staticmethod
    def strip_magic_line(source: str) -> str:
        # Filter out any magic lines (starting with %) if in a Jupyter notebook
        import re

        srclines = map(lambda x: re.sub(r"^\%.*", "", x), source.split("\n"))
        source = "\n".join(srclines)
        return source
```

**Comment by emeryberger** [comment]
Please try the repo version - thanks!

**Comment by D-VR** [comment]
Thank you for the fix!

I can confirm that this has fixed it for me, but this issue may still affect people running Jupyter Notebooks, since Pandas is a commonly used package in that environment.

It's likely to be very rare (only found the issue because I accidentally set the profiling way too frequent), and should be "fixed" by simply re-running scalene in most cases.

**Comment by emeryberger** [comment]
Thanks for testing! I think this should now be fine (based on a few tests with Pandas in a notebook) so I'm closing.
