### ISSUE TITLE
Running pytest on Charcoal-SE/Smokedetector under scalene fails

### ISSUE THREAD

**Issue by micsthepick** [plasma-umass/scalene#863]
**Describe the bug**
Pytest cannot run due to below error(s):
```
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.8.19, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/mike/sources/SmokeDetector
plugins: xdist-3.6.1, timeout-2.3.1, cov-5.0.0
timeout: 300.0s
timeout method: signal
timeout func_only: False
created: 3/3 workersScalene: could not find input file /home/mike/sources/SmokeDetector/-u
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/_pytest/main.py", line 281, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/_pytest/logging.py", line 784, in pytest_sessionstart
INTERNALERROR>     return (yield)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/xdist/dsession.py", line 90, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/xdist/workermanage.py", line 88, in setup_nodes
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/xdist/workermanage.py", line 88, in <listcomp>
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/xdist/workermanage.py", line 97, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/execnet/multi.py", line 154, in makegateway
INTERNALERROR>     gw = gateway_bootstrap.bootstrap(io, spec)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/execnet/gateway_bootstrap.py", line 88, in bootstrap
INTERNALERROR>     bootstrap_import(io, spec)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/execnet/gateway_bootstrap.py", line 36, in bootstrap_import
INTERNALERROR>     s = io.read(1)
INTERNALERROR>   File "/home/mike/.local/lib/python3.8/site-packages/execnet/gateway_base.py", line 536, in read
INTERNALERROR>     raise EOFError("expected %d bytes, got %d" % (numbytes, len(buf)))
INTERNALERROR> EOFError: expected 1 bytes, got 0
```

**To Reproduce**
(tested in WSL2) - Setup a conda env with scalene, clone github.com:charcoal-se/smokedetector.git, pip install -r requirements.txt, and run the following command (modified from a CI yaml) ```scalene --profile-all -m pytest -W default::Warning --cov=chatcommunicate --cov=findspam --cov=globalvars --cov=spamhandling --cov=datahandling --cov=chatcommands --cov=helpers -n 3 --dist loadgroup --timeout=300 test``` 

Please include a minimum working example if at all possible.

**Expected behavior**
Runs like as if I'd replaced `scalene --profile-all` with just `python`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Widows 11 Education
  - Browser Firefox
 - Version:
 
 ```bash
wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4112
```

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.
(sidenote this may be more helpful at the top of the issue template) - replicates with latest.

**Additional context**
SmokeDetector can take a while to clone (not too long), so if you think that this might be solvable without cloning it, I'd certainly recommend investigating that way.

**Comment by micsthepick** [comment]
possibly related: #82

**Comment by micsthepick** [comment]
... and what makes me think so, is the error from scalene:
> Scalene: could not find input file /home/mike/sources/SmokeDetector/-u

**Comment by emeryberger** [comment]
Can you try putting `---` after the Scalene flag(s) and before `pytest`?

**Comment by micsthepick** [comment]
@emeryberger still reproduces with the following: ```scalene --profile-all --- -m pytest -W default::Warning --cov=chatcommunicate --cov=findspam --cov=globalvars --cov=spamhandling --cov=datahandling --cov=chatcomm
ands --cov=helpers -n 3 --dist loadgroup --timeout=300 test```

**Comment by micsthepick** [comment]
just in case I needed to put `-m pytest` before the `---`, the following doesn't work either:
```scalene --profile-all -m pytest --- -W default::Warning --cov=chatcommunicate --cov=findspam --cov=globalvars --cov=spamhandling --cov=datahandling --cov=chatcomm
ands --cov=helpers -n 3 --dist loadgroup --timeout=300 test```

**Comment by mschroeder-fzj** [comment]
I have the exact same error.
It happens because scalene and the pytest-xdist plugin seemingly can't be used together. I assume scalene can't handle the worker forking by xdist.
Without the plugin `python3 -m scalene --- -m pytest ...` works.

**Comment by emeryberger** [comment]
Thanks for the reports! @mschroeder-fzj @micsthepick - it appears to have been a flag processing problem. Can you verify that the repo version works for you?

**Comment by mschroeder-fzj** [comment]
@emeryberger I would say it looks good, thanks for your effort.

Tested the `master` branch successfully for Python 3.10, 3.11, 3.12, 3.13 and 3.14.

One thing of note:
on Python 3.13 and 3.14 I got the message:
```
Scalene: The specified code did not run for long enough to profile.
By default, Scalene only profiles code in the file executed and its subdirectories.
To track the time spent in all files, use the `--profile-all` option.
```
Even though I had that option specified: `python -m scalene run --outfile profile.json --profile-all --- -m pytest ...`  
The program I tested this on is rather small and maybe on older Python Versions it was just slow enough for scalene.

**Comment by emeryberger** [comment]
That's a little concerning. Can you add some delays to the test program?

**Comment by mschroeder-fzj** [comment]
I added a loop to a function that I test with 500million iterations, which extends to test time by a lot.  
On Python 3.13 the test ran ~5min but I still get the message that the code didn't run for long enough, the same for 3.14 where it ran for ~50sec.

In case my code is too simple or my flags are set wrong, here is what I am doing:

Command:
```sh
python -m scalene run --outfile artifacts/python_version_${PYTHON_VERSION}_profile.json --profile-all --- -m pytest ${xdist_args} --junitxml=artifacts/python_results_${PYTHON_VERSION}.junit.xml --cov=src --cov-report=xml:artifacts/python_coverage_${PYTHON_VERSION}.xml --cov-report=term-missing tests/
```
Code:
```py
ITERATIONS = 500_000_000

def add(a, b):
    result = a + b
    for _ in range(ITERATIONS):
        result = result  # busy-wait to simulate heavy computation
    return result

def subtract(a, b):
    result = a - b
    for _ in range(ITERATIONS):
        result = result  # busy-wait to simulate heavy computation
    return result
```
Test:
```py
from example_project.testscript import add, subtract

ITERATIONS = 1

def test_add_profiling():
    """Runs add() n times to give Scalene enough CPU time to profile."""
    result = 0
    for i in range(ITERATIONS):
        result = add(result, i)
        result = add(result, -i)  # keep result from growing unbounded
    assert result == 0

def test_subtract_profiling():
    """Runs subtract() n times to give Scalene enough CPU time to profile."""
    result = 0
    for i in range(ITERATIONS):
        result = subtract(result, i)
        result = subtract(result, -i)  # keep result from growing unbounded
    assert result == 0
```

**Comment by emeryberger** [comment]
@mschroeder-fzj Thanks for the detailed report. We've been investigating but can't reproduce on macOS + Python 3.13/3.14 — profiling works correctly there, even through pytest with `--cov`.

Could you help us narrow this down?

1. **What OS/platform are you on?** (e.g., Ubuntu 24.04, etc.)
2. **How was Python 3.13/3.14 installed?** (e.g., system package, pyenv, deadsnakes PPA, built from source)
3. **Did you install Scalene from the master branch via `pip install -e .` (editable) or `pip install .`?**

Also, could you try running this quick diagnostic on Python 3.13?

```python
# save as debug_scalene.py
import sys, signal, threading

# Check 1: Does the C extension work?
try:
    from scalene import pywhere
    frames = pywhere.collect_frames_to_record()
    print(f"C extension: {len(frames)} frames")
except Exception as e:
    print(f"C extension error: {e}")

# Check 2: Do signals + frame collection work together?
count = [0]
empty = [0]

def handler(sig, frame):
    count[0] += 1
    try:
        from scalene import pywhere
        raw = pywhere.collect_frames_to_record()
        if not raw:
            empty[0] += 1
    except Exception as e:
        if count[0] <= 3:
            print(f"Signal handler error: {e}", file=sys.stderr)

signal.signal(signal.SIGALRM, handler)
signal.setitimer(signal.ITIMER_REAL, 0.01, 0.01)

s = 0
for i in range(5_000_000):
    s += i

signal.setitimer(signal.ITIMER_REAL, 0)
print(f"Signal handler called {count[0]} times, empty frames: {empty[0]}")
```

Run with: `python3.13 debug_scalene.py` (from the scalene repo directory, or wherever scalene is installed).

This will tell us whether the issue is in the C extension's frame collection, signal delivery, or something else entirely.

**Comment by micsthepick** [comment]
```
git clone git@github.com:charcoal-se/smokedetector.git
cd smokedetector
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt pytest-cov coveralls tld
python3 -W default::Warning -m pytest --cov=chatcommands --cov=chatcommunicate --cov=datahandling --cov=findspam --cov=globalvars --cov=helpers --cov=parsing --cov=spamhandling -n 12 --dist loadgroup --timeout=300 --durations=10 test
```
(set up and runs without scalene, one test fails due to timeout - on my machine)
```
pip install scalene
sudo python3 -m scalene.set_nvidia_gpu_modes
cat << 'EOF' > run_pytest_scalene.py
import runpy
import sys

# Simulate: python -m pytest <args>
sys.argv = ["pytest"] + sys.argv[1:]

runpy.run_module("pytest", run_name="__main__")
EOF
chmod +x run_pytest_scalene.py
scalene run --profile-all -W default::Warning run_pytest_scalene.py --cov=chatcommands --cov=chatcommunicate --cov=datahandling --cov=findspam --cov=globalvars --cov=helpers --cov=parsing --cov=spamhandling -n 12 --dist loadgroup --timeout=300 --durations=10 test
```
(run with scalene, the entire sudo command can be removed if not sudo privilidged or not linux, also note that "-n 12" can be adjusted to the machine threads count)

using the above should work fine, at least on my current linux machine @emeryberger @mschroeder-fzj  if you'd like to, create a new issue and link this one to it since the original issue seems resolved
